library(data.table)
library(ggplot2)
library(tidyverse)

#############################################################################
### file reading
### these are the files generated by modkit pileup
## this is just the example of l. acidophilus data, the one for e. coli is the same processing.
setwd("")
depth_methyl_phase_m6a <- fread("lacidophilus_pileup_depth_m6a_combine.bed")
depth_methyl_phase_m4c <- fread("lacidophilus_pileup_depth_m4c_combine.bed")
depth_methyl_phase_m5c <- fread("lacidophilus_pileup_depth_m5c_combine.bed")

#############################################################################
### functions for estimating correlation between different sequencing coverages
### summary generation function
summary_generation <- function(depth_methyl_phase){
  depth_methylation_phase_filter <- depth_methyl_phase
  
  depth_methylation_summary <- depth_methylation_phase_filter[, .(mean_modified_number = mean(modified_number),
                                                                  mean_modified_fraction = mean(modified_number/valid_coverage)), 
                                                              by = .(chrom, start, end, strand, phase, coverage)]
  
  depth_methylation_summary <- as.data.frame(depth_methylation_summary)
  
  
  depth_methylation_summary$specific_id <- paste(depth_methylation_summary$chrom, depth_methylation_summary$end, depth_methylation_summary$strand, sep="_")
  return(depth_methylation_summary)
}


### function to generate correlation matrix
corr_table_generate <- function(data_frame_summary, phase_status){
  
  ### select the phase status
  depth_methylation_summary_wider <- data_frame_summary %>%
    filter(phase==phase_status) %>%
    pivot_wider(names_from = specific_id, values_from = mean_modified_fraction, id_cols = coverage)
  
  ### add row names and convert dataframe to matrix to accelerate the calculation
  depth_methylation_summary_wider <- as.data.frame(depth_methylation_summary_wider)
  
  rownames(depth_methylation_summary_wider) <- depth_methylation_summary_wider[,"coverage"]
  depth_methylation_summary_cor_table <- depth_methylation_summary_wider[, !(names(depth_methylation_summary_wider) %in% c("coverage"))]
  
  depth_methylation_summary_cor_table <- as.matrix(depth_methylation_summary_cor_table, rownames=T)
  return(depth_methylation_summary_cor_table)
}

corr_matrix_generate <- function(corr_table, phase_status){
  corr_table <- as.data.frame(corr_table)
  corr_table <- Filter(function(x) all(!is.na(x)), corr_table)
  
  ### generate a correlation matrix
  corr_mat <- round(cor(t(corr_table)),2)
  
  get_lower_tri<-function(corr_mat){
    corr_mat[upper.tri(corr_mat)] <- NA
    return(corr_mat)
  }
  
  get_upper_tri <- function(corr_mat){
    corr_mat[lower.tri(corr_mat)]<- NA
    return(corr_mat)
  }
  
  lower_tri <- get_lower_tri(corr_mat)
  
  ### reshape the matrix to make it human-readable
  melted_cormat <- melt(lower_tri, na.rm = TRUE)
  melted_cormat$phase <- phase_status
  
  return(melted_cormat)
}

#############################################################################
### data processing using functions
### m6a data process
m6a_summary <- summary_generation(depth_methyl_phase_m6a)

exp_corr_table_m6a <- corr_table_generate(m6a_summary, "exponential")
sta_corr_table_m6a <- corr_table_generate(m6a_summary, "stationary")
exp_corr_matrix_m6a <- corr_matrix_generate(exp_corr_table_m6a, "exponential")
sta_corr_matrix_m6a <- corr_matrix_generate(sta_corr_table_m6a, "stationary")

combine_corr_matrix_m6a <- exp_corr_matrix_m6a %>%
  rbind(sta_corr_matrix_m6a)

corr_100_matrix_m6a <- subset(combine_corr_matrix_m6a, combine_corr_matrix_m6a$Var1 == "100"|combine_corr_matrix_m6a$Var2 == "100") %>%
  mutate(methylation = "m6A")


### m4c data process
m4c_summary <- summary_generation(depth_methyl_phase_m4c)

exp_corr_table_m4c <- corr_table_generate(m4c_summary, "exponential")
sta_corr_table_m4c <- corr_table_generate(m4c_summary, "stationary")
exp_corr_matrix_m4c <- corr_matrix_generate(exp_corr_table_m4c, "exponential")
sta_corr_matrix_m4c <- corr_matrix_generate(sta_corr_table_m4c, "stationary")

combine_corr_matrix_m4c <- exp_corr_matrix_m4c %>%
  rbind(sta_corr_matrix_m4c)

corr_100_matrix_m4c <- subset(combine_corr_matrix_m4c, combine_corr_matrix_m4c$Var1 == "100"|combine_corr_matrix_m4c$Var2 == "100") %>%
  mutate(methylation = "m4C")

### m5c data process
m5c_summary <- summary_generation(depth_methyl_phase_m5c)

exp_corr_table_m5c <- corr_table_generate(m5c_summary, "exponential")
sta_corr_table_m5c <- corr_table_generate(m5c_summary, "stationary")
exp_corr_matrix_m5c <- corr_matrix_generate(exp_corr_table_m5c, "exponential")
sta_corr_matrix_m5c <- corr_matrix_generate(sta_corr_table_m5c, "stationary")

combine_corr_matrix_m5c <- exp_corr_matrix_m5c %>%
  rbind(sta_corr_matrix_m5c)

corr_100_matrix_m5c <- subset(combine_corr_matrix_m5c, combine_corr_matrix_m5c$Var1 == "100"|combine_corr_matrix_m5c$Var2 == "100") %>%
  mutate(methylation = "m5C")

#############################################################################
### combine all data frame and visualization
all_methyl_correlation_lacidophilus <- corr_100_matrix_m6a %>%
  rbind(corr_100_matrix_m4c, corr_100_matrix_m5c)
all_methyl_correlation_lacidophilus$genus <- "Lactobacillus"


all_methyl_correlation_ecoli <- fread("Ecoli_seq_depth_methyl_correlation_na_remove.tsv")
all_methyl_correlation <- rbind(all_methyl_correlation_ecoli,all_methyl_correlation_lacidophilusc)

ggplot(all_methyl_correlation_lacidophilus, aes(x=Var1, y=value, color=phase)) +
  facet_wrap(vars(methylation)) +
  geom_line() +
  geom_vline(aes(xintercept=100), linetype="dashed", color="#7da66a") +
  geom_hline(aes(yintercept=0.9), linetype="dashed", color="#328cb0") +
  geom_text(aes(x=90, y=0, label="100x"), color="#7da66a") +
  geom_text(aes(x=0, y=0.93, label="0.9"), color="#328cb0") +
  theme_light() +
  labs(x= "Sequencing depth", y="Correlation") +
  scale_color_manual("Phase", breaks = c("exponential","stationary"),
                     values = c("#444574", "#cd534cff")) +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        panel.spacing = unit(1,"line"),
        text = element_text(size = 20))
