library(data.table)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggfortify)
library(grid)
library(rstatix)
library(gridExtra)
library(ggside)
library(deeptime)
library(patchwork)
library(ggbreak)

#############################################################################
#### file reading
#### these are the files generated by seqkit
setwd("")
sample_primary_length <- fread("ecoli_lacidophilus_primary_fastq_stat.tsv",sep="\t", header=TRUE)

sample_primary_length <- sample_primary_length %>%
  subset(replicate_id != "replicate_4" & replicate_id != "replicate_5")
options(scipen=999)

#############################################################################
#### statistical analysis
#### length comparison
sample_primary_length_compare <- sample_primary_length %>%
  group_by(genus) %>%
  t_test(data = ., average_length ~ phase, paired = T) %>%
  add_significance()

sample_primary_length_compare <- sample_primary_length_compare %>%
  group_by(genus) %>%
  add_xy_position(x="phase", step.increase=0.01)

#### n50 comparison
sample_primary_n50_compare <- sample_primary_length %>%
  group_by(genus) %>%
  t_test(data = ., n50 ~ phase, paired = T) %>%
  add_significance()

sample_primary_n50_compare <- sample_primary_n50_compare %>%
  group_by(genus) %>%
  add_xy_position(x="phase", step.increase=0.01)

#### seq number comparison
sample_primary_seq_number_compare <- sample_primary_length %>%
  group_by(genus) %>%
  t_test(data = ., seq_number ~ phase, paired = T) %>%
  add_significance()

sample_primary_seq_number_compare <- sample_primary_seq_number_compare %>%
  group_by(genus) %>%
  add_xy_position(x="phase", step.increase=0.001)

#### generate a summary file
sample_primary_length_summary <- sample_primary_length %>%
  group_by(genus, phase) %>%
  summarise(mean_average_length = mean(average_length),
            sd_average_length=sd(average_length),
            mean_n50 = mean(n50), 
            sd_n50=sd(n50), 
            mean_seq_number=mean(seq_number), 
            sd_seq_number=sd(seq_number), .groups = "drop")

#############################################################################
#### visualization
#### E.coli 
ecoli_length <- ggplot(sample_primary_length[sample_primary_length$genus=="Escherichia",], 
                       aes(x=phase,y=average_length)) +
  geom_boxplot(aes(fill=phase), alpha=0.7) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(sample_primary_length_compare[sample_primary_length_compare$genus=="Escherichia",], hide.ns = TRUE, coord.flip = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1) +
  scale_y_continuous(limits = c(16000, 20000)) +
  coord_trans_flip() +
  labs(y="Average length (bp)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        axis.ticks.x = element_blank()) +
  theme(text = element_text(size = 22),
        axis.text.x = element_blank(),
        legend.position = "none",
        strip.background = element_blank())

ecoli_length_ecoli_seq_number <- ggplot(sample_primary_length[sample_primary_length$genus=="Escherichia",], 
                                        aes(x=average_length,y=seq_number)) +
  stat_cor(method = "spearman", p.accuracy=0.001, size=5, label.x = 18500) +
  geom_smooth(method = "lm", linewidth=0.5, se=T, alpha=0.5) +
  geom_point(aes(color=phase), size=3) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  scale_x_continuous(limits = c(16000, 20000)) +
  scale_y_continuous(limits = c(NA, 21000)) +
  labs(x="Average length (bp)", y="Read number") +
  theme_bw() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        legend.position = "bottom") +
  theme(text = element_text(size = 22))

ecoli_seq_number <- ggplot(sample_primary_length[sample_primary_length$genus=="Escherichia",], aes(x=phase,y=seq_number)) +
  geom_boxplot(aes(fill=phase), alpha=0.7) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(sample_primary_seq_number_compare[sample_primary_seq_number_compare$genus=="Escherichia",], hide.ns = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1) +
  labs(y="Read number") +
  scale_y_continuous(limits = c(NA, 21000)) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        axis.ticks.y = element_blank()) +
  theme(text = element_text(size = 22),
        axis.text.y = element_blank(),
        legend.position = "none",
        strip.background = element_blank())
ecoli_length + plot_spacer() + ecoli_length_ecoli_seq_number + plot_layout(nrow = 3, ncol=2, heights = c(0.35,0.6, 0.05), widths = c(0.6,0.4))  + ecoli_seq_number + guide_area()

#### L.acidophilus
lacidophilus_length <- ggplot(sample_primary_length[sample_primary_length$genus=="Lactobacillus",], aes(x=phase,y=average_length)) +
  geom_boxplot(aes(fill=phase), alpha=0.7) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(sample_primary_length_compare[sample_primary_length_compare$genus=="Lactobacillus",], hide.ns = TRUE, coord.flip = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1) +
  labs(y="Average length (bp)") +
  scale_y_continuous(limits = c(500, 1750)) +
  coord_trans_flip() +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        axis.ticks.x = element_blank()) +
  theme(text = element_text(size = 22),
        axis.text.x = element_blank(),
        legend.position = "none",
        strip.background = element_blank())

lacidophilus_length_seq_number <- ggplot(sample_primary_length[sample_primary_length$genus=="Lactobacillus",], 
                                         aes(x=average_length,y=seq_number)) +
  stat_cor(method = "spearman", p.accuracy=0.001, size=5, label.x = 1300) +
  geom_smooth(method = "lm", linewidth=0.5, se=T, alpha=0.5) +
  geom_point(aes(color=phase), size=3) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  scale_y_continuous(limits = c(100000, 430000)) +
  scale_x_continuous(limits = c(500, 1750)) +
  labs(x="Average length (bp)", y="Read number") +
  theme_bw() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        legend.position = "bottom") +
  theme(text = element_text(size = 22))

lacidophilus_seq_number <- ggplot(sample_primary_length[sample_primary_length$genus=="Lactobacillus",], aes(x=phase,y=seq_number)) +
  geom_boxplot(aes(fill=phase), alpha=0.7) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  stat_pvalue_manual(sample_primary_seq_number_compare[sample_primary_seq_number_compare$genus=="Lactobacillus",], hide.ns = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1, step.increase = 1000000) +
  labs(y="Read number") +
  scale_y_continuous(limits = c(100000, 430000)) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        axis.ticks.y = element_blank()) +
  theme(text = element_text(size = 22),
        axis.text.y = element_blank(),
        legend.position = "none",
        strip.background = element_blank())

lacidophilus_length + plot_spacer() + lacidophilus_length_seq_number + plot_layout(nrow = 3, ncol=2, heights = c(0.35,0.6, 0.05), widths = c(0.6,0.4))  + lacidophilus_seq_number + guide_area()
