library(data.table)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggfortify)
library(grid)
library(rstatix)
library(janitor)
library(utils)
library(patchwork)


#############################################################################
#### file reading
#### the major file used for analysis was generated by samtools
#### ecoli
setwd("")
ecoli_oriC <- fread("ecoli_oriC_extend.bed", header=F)
ecoli_ter <- fread("ecoli_ter_extend.bed", header=F)
ecoli_other_regions <- fread("ecoli_other_regions_extend.bed", header=F)

colnames(ecoli_oriC) <- c("chromosome", "start", "end")
colnames(ecoli_ter) <- c("chromosome", "start", "end")
colnames(ecoli_other_regions) <- c("chromosome", "start", "end")

#### import the methylation data
ecoli_lacidophilus_seq_depth <- fread("ecoli_lacidophilus_seq_depth.tsv",sep="\t", header=TRUE)

ecoli_genome_slide <- fread("GCF_000008865.2_ASM886v2_windows_10kb.bed", sep="\t", header = F)
lacidophilus_genome_slide <- fread("GCF_034298135.1_ASM3429813v1_windows_10kb.bed", sep="\t", header = F)

colnames(ecoli_genome_slide) <- c("chromosome", "start", "end")
colnames(lacidophilus_genome_slide) <- c("chromosome", "start", "end")

options(scipen=999)

#############################################################################
### file claen up
ecoli_seq_depth <- ecoli_lacidophilus_seq_depth[ecoli_lacidophilus_seq_depth$chrom=="NC_002695.2" & ecoli_lacidophilus_seq_depth$genus=="Escherichia",] %>%
  filter(sample_id %in% c("ecoli_exp_1_primary", "ecoli_exp_2_primary", "ecoli_exp_3_primary", "ecoli_sta_1_primary", "ecoli_sta_2_primary", "ecoli_sta_3_primary"))
lacidophilus_seq_depth <- ecoli_lacidophilus_seq_depth[ecoli_lacidophilus_seq_depth$chrom=="NZ_CP139575.1" & ecoli_lacidophilus_seq_depth$genus=="Lactobacillus",]


#############################################################################
#### functions for analysis
#### a function to calculate regional seq depth
windows_methyl_form <- function(genome_slide_bed, seq_depth_file) {
  fraction_modified_windows <- as.data.frame(matrix(nrow=0, ncol = 7))
  colnames(fraction_modified_windows) <- c("chrom", "start", "end", "phase", "replicate",
                                           "sum_seq_depth","genus")
  
  n_iter <- length(seq_len(nrow(genome_slide_bed)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(genome_slide_bed))){
    start_label <- as.integer(genome_slide_bed[i, "start"])
    end_label <- as.integer(genome_slide_bed[i, "end"])
    chromosome <- as.character(genome_slide_bed[i, "chromosome"])
    
    inter_form <- subset(seq_depth_file,
                         seq_depth_file$position >= start_label & seq_depth_file$position < end_label & seq_depth_file$chrom == chromosome)
    
    inter_form_summary <- inter_form %>%
      group_by(chrom, phase, genus, replicate_id) %>%
      summarise(sum_seq_depth = sum(seq_depth), .groups = "drop")
    
    inter_form_summary$start <- start_label
    inter_form_summary$end <- end_label
    
    fraction_modified_windows <- rbind(fraction_modified_windows, inter_form_summary)
    setTxtProgressBar(pb, i)
  }
  cat("\n almost there")
  close(pb) # Close the connection
  return(fraction_modified_windows)
}

#### a function to calculate regional dna start site
windows_dna_site_form <- function(genome_slide_bed, dna_site_file) {
  fraction_modified_windows <- as.data.frame(matrix(nrow=0, ncol = 7))
  colnames(fraction_modified_windows) <- c("chromosome", "start", "end", "phase", "replicate",
                                           "sum_dan_site", "sum_end_site")
  
  n_iter <- length(seq_len(nrow(genome_slide_bed)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(genome_slide_bed))){
    start_label <- as.integer(genome_slide_bed[i, "start"])
    end_label <- as.integer(genome_slide_bed[i, "end"])
    chromosome <- as.character(genome_slide_bed[i, "chromosome"])
    
    inter_form_start <- subset(dna_site_file,
                               dna_site_file$start >= start_label & dna_site_file$start < end_label & dna_site_file$chromosome == chromosome)
    
    inter_form_end <- subset(dna_site_file,
                             dna_site_file$end >= start_label & dna_site_file$end < end_label & dna_site_file$chromosome == chromosome)
    
    inter_form_start_summary <- inter_form_start %>%
      group_by(chromosome, phase, replicate) %>%
      summarise(sum_start_site = n(), .groups = "drop")
    
    inter_form_end_summary <- inter_form_end %>%
      group_by(chromosome, phase, replicate) %>%
      summarise(sum_end_site = n(), .groups = "drop")
    
    inter_form_start_summary$start <- start_label
    inter_form_start_summary$end <- end_label
    
    inter_form_end_summary$start <- start_label
    inter_form_end_summary$end <- end_label
    
    inter_form_start_summary <- inter_form_start_summary%>%
      mutate(unique_id=paste(chromosome, phase, replicate, start, end, sep = "_"))
    
    inter_form_end_summary <- inter_form_end_summary%>%
      mutate(unique_id=paste(chromosome, phase, replicate, start, end, sep = "_"))
    
    inter_form_summary <- inter_form_start_summary %>%
      inner_join(inter_form_end_summary[,c("unique_id", "sum_end_site")], by="unique_id")
    
    fraction_modified_windows <- rbind(fraction_modified_windows, inter_form_summary)
    setTxtProgressBar(pb, i)
  }
  cat("\n almost there")
  close(pb) # Close the connection
  return(fraction_modified_windows)
}

#### a function to calculate the seq depth in oriC, ter, and other regions
region_seq_form <- function(genome_slide_bed, seq_depth_file, region_name) {
  fraction_modified_windows <- as.data.frame(matrix(nrow=0, ncol = 7))
  colnames(fraction_modified_windows) <- c("chrom", "start", "end", "phase", "replicate",
                                           "sum_seq_depth","genus")
  replicate_name_list <- unique(seq_depth_file$replicate)
  
  inter_addition_form <- as.data.frame(matrix(nrow=0, ncol = 10))
  colnames(inter_addition_form) <- c("chrom", "start", "end", "phase", "replicate",
                                     "sum_seq_depth","genus")
  
  n_iter <- length(seq_len(nrow(genome_slide_bed)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(genome_slide_bed))){
    start_label <- as.integer(genome_slide_bed[i, "start"])
    end_label <- as.integer(genome_slide_bed[i, "end"])
    chromosome <- as.character(genome_slide_bed[i, "chromosome"])
    
    inter_form <- subset(seq_depth_file,
                         seq_depth_file$position >= start_label & seq_depth_file$position < end_label & seq_depth_file$chrom == chromosome)
    
    inter_form_summary <- inter_form %>%
      group_by(chrom, phase, genus, replicate_id) %>%
      summarise(sum_seq_depth = sum(seq_depth), .groups = "drop")
    
    inter_form_summary$start <- start_label
    inter_form_summary$end <- end_label
    inter_form_summary$region <- region_name
    
    fraction_modified_windows <- rbind(fraction_modified_windows, inter_form_summary)
    setTxtProgressBar(pb, i)
  }
  cat("\n almost there")
  close(pb) # Close the connection
  return(fraction_modified_windows)
}

#############################################################################
#### perform seq depth analysis using functions
ecoli_seq_depth_window <- windows_methyl_form(ecoli_genome_slide, ecoli_seq_depth)
lacidophilus_seq_depth_window <- windows_methyl_form(lacidophilus_genome_slide, lacidophilus_seq_depth)

ecoli_ter_middle <- (2115426+2115454)/2
lacidophilus_ter_middle <- 759661

ecoli_origin_middle <- (4719203+4179580)/2

lacidophilus_origin_1_middle <- (1644596+1645071)/2
lacidophilus_origin_2_middle <- (1646440+1646616)/2

#### e. coli
ecoli_seq_depth_summary_wider <- ecoli_seq_depth_window %>%
  pivot_wider(names_from = phase, values_from = sum_seq_depth) %>%
  mutate(differential_seq_depth=(stationary+1)/(exponential+1),
         log2_differential_seq_depth=log2((stationary+1)/(exponential+1)))

ecoli_seq_depth_summary <- ecoli_seq_depth_summary_wider %>%
  group_by(chrom, genus, start, end) %>%
  summarise(mean_exp_depth=mean(exponential/(end-start)),
            mean_sta_depth=mean(stationary/(end-start)),
            sd_exp_depth=sd(exponential/(end-start)),
            sd_sta_depth=sd(stationary/(end-start)),
            mean_log2_seq_depth=mean(log2_differential_seq_depth), 
            sd_log2_seq_depth=sd(log2_differential_seq_depth), .groups = "drop") %>%
  mutate(rel_position_ter=((start+end)/2)-ecoli_ter_middle,
         rel_position_origin_1=((start+end)/2)-ecoli_origin_middle,
         rel_position_origin_2=((start+end)/2)-ecoli_origin_middle)

#### l. acidophilus
lacidophilus_seq_depth_wider <- lacidophilus_seq_depth_window %>%
  pivot_wider(names_from = phase, values_from = sum_seq_depth) %>%
  mutate(differential_seq_depth=(stationary+1)/(exponential+1),
         log2_differential_seq_depth=log2((stationary+1)/(exponential+1)))

lacidophilus_seq_depth_summary <- lacidophilus_seq_depth_wider %>%
  group_by(chrom, genus, start, end) %>%
  summarise(mean_exp_depth=mean(exponential/(end-start)),
            mean_sta_depth=mean(stationary/(end-start)),
            sd_exp_depth=sd(exponential/(end-start)),
            sd_sta_depth=sd(stationary/(end-start)),
            mean_log2_seq_depth=mean(log2_differential_seq_depth), 
            sd_log2_seq_depth=sd(log2_differential_seq_depth), .groups = "drop") %>%
  mutate(rel_position_ter=((start+end)/2)-lacidophilus_ter_middle,
         rel_position_origin_1=((start+end)/2)-lacidophilus_origin_1_middle,
         rel_position_origin_2=((start+end)/2)-lacidophilus_origin_2_middle)

ecoli_lacidophilus_seq_depth_summary <- rbind(ecoli_seq_depth_summary, lacidophilus_seq_depth_summary)

ecoli_lacidophilus_seq_depth_summary <- ecoli_lacidophilus_seq_depth_summary %>%
  mutate(direction_ter=ifelse(rel_position_ter>=0, "upstream", "downstream"),
         direction_rel_position_origin_1=ifelse(rel_position_origin_1>=0, "upstream", "downstream"),
         direction_rel_position_origin_2=ifelse(rel_position_origin_2>=0, "upstream", "downstream"))

ecoli_lacidophilus_seq_depth <- rbind(ecoli_seq_depth_summary_wider, lacidophilus_seq_depth_wider)

ecoli_ter_middle <- (2115426+2115454)/2
lacidophilus_ter_middle <- 759661

ecoli_origin_middle <- (4719203+4179580)/2

lacidophilus_origin_1_middle <- (1644596+1645071)/2
lacidophilus_origin_2_middle <- (1646440+1646616)/2

#############################################################################
#### visualization
#### e. coli
#### ter and oriC
ecoli_seq_depth_genome <- ggplot(ecoli_lacidophilus_seq_depth_summary[ecoli_lacidophilus_seq_depth_summary$genus=="Escherichia",], aes(x=end, y=mean_log2_seq_depth)) +
  geom_point(colour="#54a1a1", alpha=0.7, size=2) +
  geom_vline(aes(xintercept=ecoli_origin_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=ecoli_origin_middle+170000, y=4, label="oriC", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=ecoli_ter_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=ecoli_ter_middle+150000, y=4, label="ter", size=6, color = "#1d1a2f") +
  theme_bw() +
  labs(x="Genomic position (bp)", y="Log2 sequencing depth change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        legend.position = "none",
        strip.background = element_blank())

#### ter
ggplot(ecoli_lacidophilus_seq_depth_summary[ecoli_lacidophilus_seq_depth_summary$genus=="Escherichia",], aes(x=rel_position_ter, y=mean_log2_seq_depth)) +
  facet_wrap(vars(direction_ter), scales = "free_x") +
  stat_cor(method = "spearman", p.accuracy=0.001, size=7) +
  geom_point(colour="#328cb0", alpha=0.7, size=2) +
  theme_bw() +
  labs(x="Distance to DNA replication terminus (bp)", y="Log2 sequencing depth change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        legend.position = "none",
        strip.background = element_blank())

#### l. acidophilus
#### ter and oriC
lacidophilus_seq_depth_genome <- ggplot(ecoli_lacidophilus_seq_depth_summary[ecoli_lacidophilus_seq_depth_summary$genus=="Lactobacillus",], aes(x=end, y=mean_log2_seq_depth)) +
  geom_point(colour="#54a1a1", alpha=0.7, size=2) +
  geom_vline(aes(xintercept=lacidophilus_origin_1_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_origin_1_middle-80000, y=0.8, label="oriC1", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=lacidophilus_origin_2_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_origin_2_middle+80000, y=0.8, label="oriC2", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=lacidophilus_ter_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_ter_middle+60000, y=0.8, label="ter", size=6, color = "#1d1a2f") +
  theme_bw() +
  labs(x="Genomic position (bp)", y="Log2 sequencing depth change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        legend.position = "none",
        strip.background = element_blank())

#### ter
ggplot(ecoli_lacidophilus_seq_depth_summary[ecoli_lacidophilus_seq_depth_summary$genus=="Lactobacillus",], aes(x=rel_position_ter, y=mean_log2_seq_depth)) +
  facet_wrap(vars(direction_ter), scales = "free_x") +
  stat_cor(method = "spearman", p.accuracy=0.001, size=7) +
  geom_point(colour="#328cb0", alpha=0.7, size=2) +
  theme_bw() +
  labs(x="Distance to DNA replication terminus (bp)", y="Log2 sequencing depth change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        legend.position = "none",
        strip.background = element_blank())

#############################################################################
#### perform read start site analysis using functions
setwd("")
ecoli_dna_site <- fread("ecoli_dna_replication_start.tsv",sep="\t", header=TRUE)
lacidophilus_dna_site <- fread("lacidophilus_dna_replication_start.tsv",sep="\t", header=TRUE)

options(scipen=999)

ecoli_dna_site_longer <- ecoli_dna_site %>%
  pivot_longer(cols = c("start", "end"),
               names_to = "replication_site",
               values_to = "position") %>%
  filter(chromosome=="NC_002695.2",
         replicate %in% c("replicate_1", "replicate_2", "replicate_3"))

lacidophilus_dna_site_longer <- lacidophilus_dna_site %>%
  pivot_longer(cols = c("start", "end"),
               names_to = "replication_site",
               values_to = "position")

ecoli_seq_depth_oric <- region_seq_form(ecoli_oriC, ecoli_seq_depth, "oriC")
ecoli_seq_depth_ter <- region_seq_form(ecoli_ter, ecoli_seq_depth, "ter")
ecoli_seq_depth_others <- region_seq_form(ecoli_other_regions, ecoli_seq_depth, "others")

ecoli_seq_depth_all_regions <- rbind(ecoli_seq_depth_oric, ecoli_seq_depth_ter, ecoli_seq_depth_others)
ecoli_seq_depth_all_regions_summary <- ecoli_seq_depth_all_regions %>%
  group_by(chrom, phase, genus, region) %>%
  summarise(mean_sum_seq_depth = mean(sum_seq_depth), .groups = "drop")

#############################################################################
#### visualization
ecoli_position_density <- ggplot(data = ecoli_dna_site_longer[ecoli_dna_site_longer$replication_site=="start",], aes(x=position, color=phase, fill=phase)) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  geom_density(alpha = .4) +
  theme_void() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank()) +
  theme(text = element_text(size = 22),
        legend.title = element_text(face="bold"),
        legend.position = "bottom")
ecoli_position_density + ecoli_seq_depth_genome + guide_area() + plot_layout(nrow = 3, heights = c(0.2, 0.7, 0.1)) + plot_layout(guides = "collect")


lacidophilus_position_density <- ggplot(data = lacidophilus_dna_site_longer[lacidophilus_dna_site_longer$replication_site=="start",], aes(x=position, color=phase, fill=phase)) +
  scale_color_manual("Phase", breaks=c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  geom_density(alpha = .4) +
  theme_void() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank()) +
  theme(text = element_text(size = 22),
        legend.title = element_text(face="bold"),
        legend.position = "bottom")

lacidophilus_position_density + lacidophilus_seq_depth_genome + guide_area() + plot_layout(nrow = 3, heights = c(0.2, 0.7, 0.1)) + plot_layout(guides = "collect")
