library(data.table)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggfortify)
library(grid)
library(ggvenn)
library(janitor)

#############################################################################
##### file reading
##### these are the files generated by ecoli_dmr or ecoli_deseq2 rscripts
setwd("")

#### import the methylation data
gene_id_gene_body_all_methyl <- fread("gene_list_gene_body_all_methyl.tsv",sep="\t", header=F)
gene_id_promoter_all_methyl <- fread("gene_list_promoter_all_methyl.tsv",sep="\t", header=F)

gene_id_gene_body_m6A <- fread("gene_list_gene_body_m6A.tsv",sep="\t", header=F)
gene_id_promoter_m6A <- fread("gene_list_promoter_m6A.tsv",sep="\t", header=F)

gene_id_gene_body_m4C <- fread("gene_list_gene_body_m4C.tsv",sep="\t", header=F)
gene_id_promoter_m4C <- fread("gene_list_promoter_m4C.tsv",sep="\t", header=F)

gene_id_gene_body_m5C <- fread("gene_list_gene_body_m5C.tsv",sep="\t", header=F)
gene_id_promoter_m5C <- fread("gene_list_promoter_m5C.tsv",sep="\t", header=F)

#### import the rna_seq data
gene_id_rna_seq <- fread("ecoli_growth_phase_deseq2_gene_id_sig.tsv",sep="\t", header=F)
options(scipen=999)


#############################################################################
##### functions to check overlapping gene ids
gene_methyl_rna_overlap <- function(gene_methyl_clean, gene_rna_seq) {
  gene_methyl_clean_vec <- as.character(unlist(as.vector((gene_methyl_clean))))
  gene_rna_seq_clean_vec <- as.character(unlist(as.vector(gene_rna_seq)))
  
  gene_methyl_rna_list <- gene_methyl_clean_vec %>%
    subset(gene_methyl_clean_vec %in% gene_rna_seq_clean_vec)  %>%
    unique() %>%
    as.data.frame()
  return(gene_methyl_rna_list)
}

gene_methyl_rna_venn <- function(gene_methyl_clean, gene_rna_seq, title_name){
  gene_methyl_clean_vec <- as.character(unlist(as.vector((gene_methyl_clean))))
  gene_rna_seq_clean_vec <- as.character(unlist(as.vector(gene_rna_seq)))
  
  gene_id_methyl_rna_seq <- list(
    Differentially_methylated = gene_methyl_clean_vec,
    Differnetially_expressed = gene_rna_seq_clean_vec)
  
  gene_id_methyl_rna_seq_stack <- stack(gene_id_methyl_rna_seq)
  
  gene_id_methyl_rna_seq_stack_wider <- gene_id_methyl_rna_seq_stack %>%
    pivot_wider(names_from = values, values_from = values, id_cols = ind)
  
  gene_id_methyl_rna_seq_stack_wider[] <- lapply(gene_id_methyl_rna_seq_stack_wider, as.character)
  
  gene_id_methyl_rna_seq_stack_wider_long <- rbind(names(gene_id_methyl_rna_seq_stack_wider), gene_id_methyl_rna_seq_stack_wider) %>%
    t() %>%
    row_to_names(row_number = 1) %>%
    as.tibble()
  
  gene_id_methyl_rna_seq_stack_wider_long[,-1] <- lapply(gene_id_methyl_rna_seq_stack_wider_long[,-1], function(x) ifelse(is.na(x), FALSE, TRUE))
  
  venn <- ggplot(gene_id_methyl_rna_seq_stack_wider_long, aes(A=Differentially_methylated, B=Differnetially_expressed)) +
    geom_venn(set_names = c("DMGs","DEGs"),
              stroke_size = 0.8,
              text_size = 5,
              show_percentage = T,
              fill_alpha = 0.5,
              auto_scale = F,
              fill_color = c("#756bb1", "#CD534CFF")) +
    theme_void() +
    labs(title = title_name) +
    theme_void() +
    coord_fixed() +
    theme(plot.title = element_text(hjust = 0.5, vjust = -10, size=18, face = "bold"))
  return(venn)
}

#############################################################################
##### execute functions to identify overlaping genes between daatsets
#### gene id lists
gene_id_all_methyl <- rbind(gene_id_gene_body_all_methyl, gene_id_promoter_all_methyl)
gene_id_all_methyl_clean <- unique(gene_id_all_methyl)

gene_id_m6A_all <- rbind(gene_id_gene_body_m6A, gene_id_promoter_m6A)
gene_id_m6A_all_clean <- unique(gene_id_m6A_all)

gene_id_m4C_all <- rbind(gene_id_gene_body_m4C, gene_id_promoter_m4C)
gene_id_m4C_all_clean <- unique(gene_id_m4C_all)

gene_id_m5C_all <- rbind(gene_id_gene_body_m5C, gene_id_promoter_m5C)
gene_id_m5C_all_clean <- unique(gene_id_m5C_all)

gene_id_methyl_all_rna_list <- gene_methyl_rna_overlap(gene_id_all_methyl_clean, gene_id_rna_seq)

gene_id_m6A_list <- gene_methyl_rna_overlap(gene_id_m6A_all_clean, gene_id_rna_seq)
gene_id_m4C_list <- gene_methyl_rna_overlap(gene_id_m4C_all_clean, gene_id_rna_seq)
gene_id_m5C_list <- gene_methyl_rna_overlap(gene_id_m5C_all_clean, gene_id_rna_seq)

#### visualize in venn graph
gene_methyl_rna_venn(gene_id_all_methyl_clean, gene_id_rna_seq, "All DNA Methylation Forms")
gene_methyl_rna_venn(gene_id_m6A_all_clean, gene_id_rna_seq, "m6A")
gene_methyl_rna_venn(gene_id_m4C_all_clean, gene_id_rna_seq, "m4C")
gene_methyl_rna_venn(gene_id_m5C_all_clean, gene_id_rna_seq, "m5C")

