library(data.table)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggfortify)
library(grid)
library(ggvenn)
library(janitor)
library(patchwork)
library(glue)

#############################################################################
#### file reading
#### these are the files generated by dmr r script and desea2
#### import the methylation data
setwd("")
gene_id_promoter_gene_body_all_methyl <- fread("ecoli_promoter_gene_body_gene_id_all_motif.tsv",sep="\t", header=F)
gene_id_promoter_gene_body_m6A <- fread("ecoli_promoter_gene_body_gene_id_m6A_motif.tsv",sep="\t", header=F)
gene_id_promoter_gene_body_m4C <- fread("ecoli_promoter_gene_body_gene_id_m4C_motif.tsv",sep="\t", header=F)
gene_id_promoter_gene_body_m5C <- fread("ecoli_promoter_gene_body_gene_id_m5C_motif.tsv",sep="\t", header=F)

#### import the rna_seq data
ecoli_phase_deseq2 <- fread("ecoli_growth_phase_deseq2_results.tsv",sep="\t", header=TRUE)
ecoli_phase_functional_chart <- fread("Functional_Annotation_Chart.tsv",sep="\t", header=TRUE)
options(scipen=999)

gene_id_rna_seq <- fread("ecoli_growth_phase_deseq2_gene_id_sig.tsv",sep="\t", header=F)

#### import genomic element files
ecoli_gene_body <- fread("GCF_000008865.2_ASM886v2_genomic_gene.tsv", sep="\t", header = F)
colnames(ecoli_gene_body) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")

#############################################################################
#### modify the methyl files and file integration
gene_id_m6A_all_clean <- unique(gene_id_promoter_gene_body_m6A)
gene_id_m4C_all_clean <- unique(gene_id_promoter_gene_body_m4C)
gene_id_m5C_all_clean <- unique(gene_id_promoter_gene_body_m5C)

gene_id_m6A_m4C_all_clean <- unique(rbind(gene_id_m6A_all_clean, gene_id_m4C_all_clean))
gene_id_m6A_m5C_all_clean <- unique(rbind(gene_id_m6A_all_clean, gene_id_m5C_all_clean))
gene_id_m4C_m5C_all_clean <- unique(rbind(gene_id_m4C_all_clean, gene_id_m5C_all_clean))

gene_id_all_methyl_clean <- unique(gene_id_promoter_gene_body_all_methyl)


#############################################################################
#### functions for generating venn graph and list with overlapping genes
gene_methyl_rna_overlap <- function(gene_methyl_clean, gene_rna_seq) {
  gene_methyl_clean_vec <- as.character(unlist(as.vector((gene_methyl_clean))))
  gene_rna_seq_clean_vec <- as.character(unlist(as.vector(gene_rna_seq)))
  
  gene_methyl_rna_list <- gene_methyl_clean_vec %>%
    subset(gene_methyl_clean_vec %in% gene_rna_seq_clean_vec)  %>%
    unique() %>%
    as.data.frame()
  return(gene_methyl_rna_list)
}

gene_methyl_rna_venn <- function(gene_methyl_clean, gene_rna_seq, title_name){
  gene_methyl_clean_vec <- as.character(unlist(as.vector((gene_methyl_clean))))
  gene_rna_seq_clean_vec <- as.character(unlist(as.vector(gene_rna_seq)))
  
  gene_id_methyl_rna_seq <- list(
    Differentially_methylated = gene_methyl_clean_vec,
    Differnetially_expressed = gene_rna_seq_clean_vec)
  
  gene_id_methyl_rna_seq_stack <- stack(gene_id_methyl_rna_seq)
  
  gene_id_methyl_rna_seq_stack_wider <- gene_id_methyl_rna_seq_stack %>%
    pivot_wider(names_from = values, values_from = values, id_cols = ind)
  
  gene_id_methyl_rna_seq_stack_wider[] <- lapply(gene_id_methyl_rna_seq_stack_wider, as.character)
  
  gene_id_methyl_rna_seq_stack_wider_long <- rbind(names(gene_id_methyl_rna_seq_stack_wider), gene_id_methyl_rna_seq_stack_wider) %>%
    t() %>%
    row_to_names(row_number = 1) %>%
    as.tibble()
  
  gene_id_methyl_rna_seq_stack_wider_long[,-1] <- lapply(gene_id_methyl_rna_seq_stack_wider_long[,-1], function(x) ifelse(is.na(x), FALSE, TRUE))
  
  venn <- ggplot(gene_id_methyl_rna_seq_stack_wider_long, aes(A=Differentially_methylated, B=Differnetially_expressed)) +
    geom_venn(set_names = c("DMGs","DEGs"),
              stroke_size = 0.8,
              text_size = 4,
              show_percentage = T,
              fill_alpha = 0.5,
              auto_scale = F,
              fill_color = c("#756bb1", "#CD534CFF")) +
    theme_void() +
    labs(title = title_name) +
    theme_void() +
    coord_fixed() +
    theme(plot.title = element_text(hjust = 0.5, vjust = -10, size=18, face = "bold"))
  return(venn)
}


fisher_exact_test <- function(gene_methyl_clean, gene_rna_seq, genome_size) {
  gene_list <- list()
  
  gene_methyl_clean_list <- strsplit(as.vector(unique(as.character(gene_methyl_clean$V1))), ",")
  gene_rna_seq_list <- strsplit(as.vector(unique(as.character(gene_rna_seq$V1))), ",")
  
  gene_list[[glue("methyl")]] <- gene_methyl_clean_list
  gene_list[[glue("rna")]] <- gene_rna_seq_list
  
  
  common <- length(intersect(gene_list[["methyl"]], gene_list[["rna"]]))
  methyl_unique <- length(setdiff(gene_list[["methyl"]], gene_list[["rna"]]))
  rna_unique <- length(setdiff(gene_list[["rna"]], gene_list[["methyl"]]))
  
  fisher_forms <- matrix(c(common, methyl_unique, rna_unique, genome_size-common-methyl_unique-rna_unique), nrow = 2)
  
  return_list <- list()
  return_list[[1]] <- fisher_forms
  return_list[[2]] <- fisher.test(fisher_forms, alternative = "greater")
  
  return(return_list)
}

#############################################################################
### execute functions to generate gene list and venn graph
gene_id_methyl_all_rna_list <- gene_methyl_rna_overlap(gene_id_all_methyl_clean, gene_id_rna_seq)

#### one motifs
ecoli_m6a_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m6A_all_clean, gene_id_rna_seq, "G-m6A-TC") +
  labs(tag = "A") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_m4c_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m4C_all_clean, gene_id_rna_seq, "GATCNT-m4C") +
  labs(tag = "B") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_m5c_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m5C_all_clean, gene_id_rna_seq, "C-m5C-WGG") +
  labs(tag = "C") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

#### two motifs
ecoli_m6a_m4c_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m6A_m4C_all_clean, gene_id_rna_seq, "G-m6A-TC, GATCNT-m4C") +
  labs(tag = "D") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_m6a_m5c_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m6A_m5C_all_clean, gene_id_rna_seq, "G-m6A-TC, C-m5C-WGG") +
  labs(tag = "E") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_m5c_m4c_motif_rna_venn <- gene_methyl_rna_venn(gene_id_m4C_m5C_all_clean, gene_id_rna_seq, "GATCNT-m4C, C-m5C-WGG") +
  labs(tag = "F") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

#### three motifs
ecoli_all_motif_rna_venn <- gene_methyl_rna_venn(gene_id_all_methyl_clean, gene_id_rna_seq, "G-m6A-TC, GATCNT-m4C, C-m5C-WGG") +
  labs(tag = "G") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_m6a_motif_rna_venn + ecoli_m4c_motif_rna_venn + ecoli_m5c_motif_rna_venn +
  ecoli_m6a_m4c_motif_rna_venn + ecoli_m6a_m5c_motif_rna_venn + ecoli_m5c_m4c_motif_rna_venn +
  ecoli_all_motif_rna_venn + plot_layout(nrow = 3, ncol=3, heights = c(1,1,1), widths = c(1,1,1))

#############################################################################
### fisher exact test for statistics
gene_background_number <- length(ecoli_gene_body$id)

fisher_exact_test(gene_id_m6A_all_clean, gene_id_rna_seq, gene_background_number)[2]
fisher_exact_test(gene_id_m4C_all_clean, gene_id_rna_seq, gene_background_number)[2]
fisher_exact_test(gene_id_m5C_all_clean, gene_id_rna_seq, gene_background_number)[2]

fisher_exact_test(gene_id_m6A_m4C_all_clean, gene_id_rna_seq, gene_background_number)[2]
fisher_exact_test(gene_id_m6A_m5C_all_clean, gene_id_rna_seq, gene_background_number)[2]
fisher_exact_test(gene_id_m4C_m5C_all_clean, gene_id_rna_seq, gene_background_number)[2]

fisher_exact_test(gene_id_all_methyl_clean, gene_id_rna_seq, gene_background_number)[2]


fisher_exact_test(gene_id_m6A_all_clean, gene_id_rna_seq, gene_background_number)[1]
fisher_exact_test(gene_id_m4C_all_clean, gene_id_rna_seq, gene_background_number)[1]
fisher_exact_test(gene_id_m5C_all_clean, gene_id_rna_seq, gene_background_number)[1]

fisher_exact_test(gene_id_m6A_m4C_all_clean, gene_id_rna_seq, gene_background_number)[1]
fisher_exact_test(gene_id_m6A_m5C_all_clean, gene_id_rna_seq, gene_background_number)[1]
fisher_exact_test(gene_id_m4C_m5C_all_clean, gene_id_rna_seq, gene_background_number)[1]

fisher_exact_test(gene_id_all_methyl_clean, gene_id_rna_seq, gene_background_number)[1]