library(data.table)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(ggfortify)
library(grid)
library(janitor)
library(Hmisc)
library(susieR)
library(lme4)
library(patchwork)


#############################################################################
##### file reading
##### these are the files generated by modkit pileup, modekit dmr, and deseq2
#### dna
setwd("")
ecoli_methyl_position_combine_filter <- fread("ecoli_methyl_position_combine_filter.tsv",sep="\t", header=TRUE)
ecoli_gene_body_promoter_position_differntial_combine <- fread("ecoli_growth_phase_diffferential_metyhl_position_gene.tsv",sep="\t", header=TRUE)

ecoli_gene_body_promoter_position_differntial_combine <- ecoli_gene_body_promoter_position_differntial_combine %>%
  mutate(unique_id=paste(chrom, start, end, strand, modified_base_code, sep = "_"))

ecoli_gene_body_promoter_position_differntial_combine_distinct <- ecoli_gene_body_promoter_position_differntial_combine %>%
  distinct(unique_id, .keep_all = T)

ecoli_methyl_gene_position_filter <- ecoli_methyl_position_combine_filter %>%
  inner_join(ecoli_gene_body_promoter_position_differntial_combine_distinct[,c("region", "unique_id", "id", "locus_tag", "symbol")], by="unique_id")

#### rna
setwd("")
ecoli_normalized_rna_seq_read <- fread("ecoli_growth_phase_deseq2_normalized_reads_rld.tsv",sep="\t", header=TRUE)
rna_seq_sig_id <- fread("ecoli_growth_phase_deseq2_gene_id_sig.tsv", sep="\t", header = F)
colnames(rna_seq_sig_id) <- "id"

ecoli_normalized_rna_seq_read_longer <- ecoli_normalized_rna_seq_read %>%
  pivot_longer(cols = exp_replicate_1:sta_replicate_3,
               names_to = c("phase", "replicate_id"),
               names_pattern = "(...)_(.*)",
               values_to = "normalized_count")

ecoli_normalized_rna_seq_read_longer$phase <- ifelse(ecoli_normalized_rna_seq_read_longer$phase=="exp", "exponential", "stationary")

ecoli_methyl_gene_position_filter <- ecoli_methyl_gene_position_filter %>%
  mutate(gene_count_replicate_id=paste(id, phase, replicate, sep="_"))

ecoli_normalized_rna_seq_read_longer <- ecoli_normalized_rna_seq_read_longer %>%
  mutate(gene_count_replicate_id=paste(id, phase, replicate_id, sep="_")) %>%
  mutate(gene_id=gsub("GeneID:","",ecoli_normalized_rna_seq_read_longer$id)) %>%
  mutate(phase_replicate=paste(phase, replicate_id, sep = "_"))


ecoli_methyl_gene_position_normalized_rna_seq <- ecoli_methyl_gene_position_filter %>%
  inner_join(ecoli_normalized_rna_seq_read_longer[,c("normalized_count", "gene_count_replicate_id")], by="gene_count_replicate_id")

ecoli_methyl_gene_position_normalized_rna_seq$id <- gsub("GeneID:", "", ecoli_methyl_gene_position_normalized_rna_seq$id)

ecoli_methyl_gene_position_normalized_rna_seq <- ecoli_methyl_gene_position_normalized_rna_seq[ecoli_methyl_gene_position_normalized_rna_seq$id %in% rna_seq_sig_id$id,]

#############################################################################
##### functions to perform linear correlation and bootstrapping
### linear model with phase and replicate
test_assoc_linear_replicate_coef = function(X,y,Z,H) {
  #####################
  ## res$betahat for Estimated effect sizes (regression coefficients).
  ## res$sebetahat for Standard errors of these estimates.
  #####################
  
  res_p_values = numeric(ncol(X))
  
  for (i in 1:ncol(X)){
    # print(i)
    phenotype = y
    marker = X[,i]
    Z=as.factor(Z)
    H=as.factor(H)
    model_data = data.frame(phenotype, marker, phase = Z, replicate=H)
    
    
    res_1 = lm(phenotype~marker+phase+replicate, data = model_data)
    res_2 = lm(phenotype~phase+replicate, data = model_data)
    
    anova_res = anova(res_2, res_1)
    f_p_value = anova_res[2, "Pr(>F)"]
    betahat = coef(res_1)["marker"]
    
    res_p_values[i] = betahat
  }
  return(res_p_values)
}

test_assoc_linear_co_pvalue_replicate = function(X,y,Z,H) {
  ##########################################
  ## res$betahat is Estimated effect sizes (regression coefficients).
  ## res$sebetahat is Standard errors of these estimates.
  ##########################################
  res_p_values <- data.frame(matrix(nrow = 0, ncol = 2))
  colnames(res_p_values) <- c("coef", "p_values")
  
  for (i in colnames(X)){
    # print(i)
    phenotype = y
    marker = X[,i]
    Z=as.factor(Z)
    H=as.factor(H)
    
    model_data = data.frame(phenotype, marker, phase = Z, replicate=H)
    
    res_1 = lm(phenotype~marker+phase+replicate, data = model_data)
    res_2 = lm(phenotype~phase+replicate, data = model_data)
    
    anova_res = anova(res_2, res_1)
    f_p_value = anova_res[2, "Pr(>F)"]
    betahat = coef(res_1)["marker"]
    
    res_p_values[i,"coef"] = betahat ## converts one-tailed p-values into two-tailed p-values
    res_p_values[i,"p_values"]=f_p_value
  }
  return(res_p_values)
}

boostrap_test_perm_1_linear_replicate_coef <- function(X,y,Z,H,K) {
  coef_orig = test_assoc_linear_replicate_coef(X,y,Z,H)
  p_orig_table = test_assoc_linear_co_pvalue_replicate(X,y,Z,H)
  position = colnames(X)
  set.seed(1727)
  null = numeric(K)
  for (i in 1:K) {
    p_boostrap = test_assoc_linear_replicate_coef(X,sample(y, replace = T),Z,H)
    null[i] <- p_boostrap
  }
  ci_95 <- quantile(null, c(0.025, 0.975), na.rm = T)

  ci_99 <- quantile(null, c(0.005, 0.995), na.rm = T)

  ci_999 <- quantile(null, c(0.0005, 0.9995), na.rm = T)

  p_test <- ifelse(!(ci_999[1] <= coef_orig && coef_orig <= ci_999[2]), 0.001, 
                   ifelse(!(ci_99[1] <= coef_orig && coef_orig <= ci_99[2]), 0.01, 
                          ifelse(!(ci_95[1] <= coef_orig && coef_orig <= ci_95[2]), 0.05, "ns")))

  p_boostrap_table=data.frame(p_boostrap_test = p_test, row.names = position)
  p_asso_p_boostrap <- cbind(p_orig_table, p_boostrap_table)
  return(p_asso_p_boostrap)
}

gene_loop_perm_linear_replicate <- function(ecoli_methyl_gene_position_normalized_rna_seq, ecoli_normalized_rna_seq_read_longer, K=1000){
  ecoli_methyl_gene_position_normalized_rna_seq <- as.data.frame(ecoli_methyl_gene_position_normalized_rna_seq)
  
  gene_asso_list <- list()
  gene_symbol_methyl_rna <- unique(ecoli_methyl_gene_position_normalized_rna_seq$symbol)
  
  
  ecoli_methyl_gene_position_normalized_rna_seq <- ecoli_methyl_gene_position_normalized_rna_seq %>%
    mutate(phase_replicate=paste(phase, replicate, sep = "_"),
           chrom_end_modified_base_code=paste(chrom, end, modified_base_code, sep = "_"))
  
  n_iter <- length(gene_symbol_methyl_rna)
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  i=1
  
  for (gene_symbol in gene_symbol_methyl_rna){
    print(gene_symbol)
    ecoli_methyl_gene_rna_subset <- ecoli_methyl_gene_position_normalized_rna_seq %>% 
      subset(symbol==gene_symbol)
    
    ecoli_methyl_gene_rna_subset_wider <- ecoli_methyl_gene_rna_subset %>%
      pivot_wider(names_from = phase_replicate, values_from = fraction_modified, id_cols = chrom_end_modified_base_code, values_fill=0) %>%
      column_to_rownames(var="chrom_end_modified_base_code")
    
    t_ecoli_methyl_gene_rna_subset_wider <- as.matrix(t(ecoli_methyl_gene_rna_subset_wider))
    
    gene_rna <- ecoli_normalized_rna_seq_read_longer[,c("normalized_count", "phase_replicate","gene_id")] %>%
      subset(gene_id %in% ecoli_methyl_gene_rna_subset$id & phase_replicate %in% rownames(t_ecoli_methyl_gene_rna_subset_wider)) %>%
      distinct(phase_replicate, .keep_all = T) %>%
      column_to_rownames(var="phase_replicate") %>%
      select(-gene_id) %>%
      as.matrix()
    
    phase_effect <- ecoli_methyl_gene_rna_subset %>%
      select(phase, phase_replicate) %>%
      distinct(phase_replicate, .keep_all = T) %>%
      column_to_rownames(var="phase_replicate")
    
    biological_effect <- ecoli_methyl_gene_rna_subset %>%
      select(replicate, phase_replicate) %>%
      distinct(phase_replicate, .keep_all = T) %>%
      column_to_rownames(var="phase_replicate")
    
    biological_effect$replicate <- as.factor(biological_effect$replicate)
    phase_effect$phase <- as.factor(phase_effect$phase)
    
    if (nlevels(phase_effect$phase) < 2 | nlevels(biological_effect$replicate) < 2) {
      setTxtProgressBar(pb, i)
      i = i + 1
      next
    }
    else{
      biological_effect <- as.matrix(biological_effect)
      phase_effect <- as.matrix(phase_effect)
      p_perm_1 = boostrap_test_perm_1_linear_replicate(t_ecoli_methyl_gene_rna_subset_wider, gene_rna, phase_effect, biological_effect, K)
      gene_asso_list[[gene_symbol]] <- as.data.frame(p_perm_1)
      setTxtProgressBar(pb, i)
      i = i + 1
    }
  }
  cat("\n finished!")
  close(pb) # Close the connection
  return(gene_asso_list)
}

### gene extract and summary adjustment
gene_assoc_extract <- function(gene_loop_perm_list, position){
  
  combo_form <- data.frame()
  
  n_iter <- length(gene_loop_perm_list)
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  i=1
  
  for (gene_symbol in names(gene_loop_perm_list)){
    inter_form <- gene_loop_perm_list[[gene_symbol]]
    inter_form$symbol <- gene_symbol
    inter_form$chrom_end_modified_base_code <- rownames(inter_form)
    inter_form$region <- position
    combo_form <- rbind(combo_form, inter_form)
    
    setTxtProgressBar(pb, i)
    i = i + 1
  }
  cat("\n 风吹仙袂飘飖举，犹似霓裳羽衣舞")
  close(pb) # Close the connection
  return(combo_form)
}

summary_adjust <- function(counting_summary){
  modified_code <- c("m4C", "m5C", "m6A")
  region<- c("gene_body", "promoter")
  gene_expression_effect <- c("positive", "negative", "none")
  
  
  inter_form_counting <- as.data.frame(matrix(nrow=0, ncol = 4))
  colnames(inter_form_counting) <- c("region", "modified_code","expression_effect", "sum_effect_poistion" )
  
  inter_form_binding <- as.data.frame(matrix(nrow=0, ncol = 4))
  colnames(inter_form_binding) <- c("region", "modified_code","expression_effect", "sum_effect_poistion" )
  
  for (code in modified_code){
    for (gene_region in region) {
      for (gene_effect in gene_expression_effect) {
        summary_subset <- counting_summary %>%
          subset(region == gene_region & modified_code==code & expression_effect==gene_effect)
        if (nrow(summary_subset)==0) {
          print(summary_subset)
          print(paste(code, gene_region, gene_effect, sep = "_"))
          inter_form_counting <- inter_form_counting[0,]
          inter_form_counting[1,"region"] <- gene_region
          inter_form_counting[1,"modified_code"] <- code
          inter_form_counting[1,"expression_effect"] <- gene_effect
          inter_form_counting[1,"sum_effect_poistion"] <- 0
          inter_form_binding <- rbind(inter_form_binding, inter_form_counting)
        } else {
          next
        }
      }
    }
  }
  
  filled_summary <- rbind(counting_summary, inter_form_binding) %>%
    group_by(region, modified_code) %>%
    mutate(percentage=100*sum_effect_poistion/sum(sum_effect_poistion))
  return(filled_summary)
}

### position cleannig using repliate number
methyl_rna_position_cleaning <- function(methyl_rna_gene){
  methyl_rna_replicate_removal_1 <- methyl_rna_gene %>%
    group_by(unique_id, id) %>%
    summarise(replicate_number = length(unique(replicate)), .groups = "drop") %>%
    filter(replicate_number==1)
  
  methyl_rna_gene_clean_1 <- methyl_rna_gene[!(methyl_rna_gene$unique_id%in%methyl_rna_replicate_removal_1$unique_id),]
  
  return(methyl_rna_gene_clean_1)
}

#############################################################################
##### perfrom linear model analysis
ecoli_methyl_rna_gene_body <- ecoli_methyl_gene_position_normalized_rna_seq[ecoli_methyl_gene_position_normalized_rna_seq$region=="gene_body",]
ecoli_methyl_rna_promoter <- ecoli_methyl_gene_position_normalized_rna_seq[ecoli_methyl_gene_position_normalized_rna_seq$region=="promoter",]

ecoli_methyl_rna_promoter_filter <- methyl_rna_position_cleaning(ecoli_methyl_rna_promoter)
ecoli_methyl_rna_gene_body_filter <- methyl_rna_position_cleaning(ecoli_methyl_rna_gene_body)

#### promoter
promoter_linear_phase_replicate <- gene_loop_perm_linear_replicate(ecoli_methyl_rna_promoter_filter, ecoli_normalized_rna_seq_read_longer)
promoter_assoc_combo_linear_phase_replicate <- gene_assoc_extract(promoter_linear_phase_replicate, "promoter")

promoter_assoc_combo_linear_phase_replicate_tsv <- promoter_assoc_combo_linear_phase_replicate
promoter_assoc_combo_linear_phase_replicate_tsv$null_distribution <- lapply(promoter_assoc_combo_linear_phase_replicate_tsv$null_distribution, function(x) paste(x, collapse = ","))
promoter_assoc_combo_linear_phase_replicate_tsv$null_distribution <- unlist(promoter_assoc_combo_linear_phase_replicate_tsv$null_distribution)

#### gene body
gene_body_linear_phase_replicate <- gene_loop_perm_linear_replicate(ecoli_methyl_rna_gene_body_filter, ecoli_normalized_rna_seq_read_longer)
gene_body_assoc_combo_linear_phase_replicate <- gene_assoc_extract(gene_body_linear_phase_replicate, "gene_body")

gene_body_assoc_combo_linear_phase_replicate_tsv <- gene_body_assoc_combo_linear_phase_replicate
gene_body_assoc_combo_linear_phase_replicate_tsv$null_distribution <- lapply(gene_body_assoc_combo_linear_phase_replicate_tsv$null_distribution, function(x) paste(x, collapse = ","))
gene_body_assoc_combo_linear_phase_replicate_tsv$null_distribution <- unlist(gene_body_assoc_combo_linear_phase_replicate_tsv$null_distribution)

write_tsv(promoter_assoc_combo_linear_phase_replicate_tsv, "promoter_assoc_combo_linear_phase_replicate_bootstrap.tsv")
write_tsv(gene_body_assoc_combo_linear_phase_replicate_tsv, "gene_body_assoc_combo_linear_phase_replicate_bootstrap.tsv")

#############################################################################
##### perfrom linear model analysis
setwd("")
promoter_assoc_combo_linear_phase_replicate_bootstrap <- fread("promoter_assoc_combo_linear_phase_replicate_bootstrap.tsv",sep="\t", header=TRUE)
gene_body_assoc_combo_linear_phase_replicate_bootstrap <- fread("gene_body_assoc_combo_linear_phase_replicate_bootstrap.tsv",sep="\t", header=TRUE)

promoter_gene_body_assoc_combo_linear_phase_replicate_bootstrap <- rbind(promoter_assoc_combo_linear_phase_replicate_bootstrap, 
                                                                         gene_body_assoc_combo_linear_phase_replicate_bootstrap)


ecoli_deseq2_results_sig <- fread("ecoli_growth_phase_deseq2_results_sig.tsv",sep="\t", header=TRUE)
ecoli_deseq2_results_sig$id <- gsub("GeneID:", "", ecoli_deseq2_results_sig$id)

gene_symbol_id <- ecoli_methyl_gene_position_normalized_rna_seq[, c("id", "symbol")] %>%
  distinct(id, .keep_all = T)

ecoli_deseq2_results_sig <- ecoli_deseq2_results_sig %>%
  inner_join(gene_symbol_id, by="id")

promoter_gene_body_assoc_combo_linear_phase_replicate_bootstrap <- promoter_gene_body_assoc_combo_linear_phase_replicate_bootstrap %>%
  inner_join(ecoli_deseq2_results_sig[,c("log2FoldChange","symbol")], by="symbol", relationship = "many-to-many")

promoter_gene_body_sig_effect_modified_linear_phase_replicate <- promoter_gene_body_assoc_combo_linear_phase_replicate_bootstrap %>%
  group_by(region, chrom_end_modified_base_code) %>%
  mutate(chrom = str_extract(chrom_end_modified_base_code, "^[A-Za-z0-9_]+\\.[0-9]+"),
         end = str_extract(chrom_end_modified_base_code, "(?<=_)\\d+(?=_)"),
         modified_code = str_extract(chrom_end_modified_base_code, "m(6|5|4)(C|A)"),
         significance = ifelse(!is.na(p_boostrap_test) & p_boostrap_test <= 0.05, "yes", "no"),
         expression_effect = ifelse(significance=="no", "none",
                                    ifelse(coef>0, "positive",
                                           ifelse(coef<0, "negative", "none"))))

promoter_gene_body_modified_linear_phase_replicate_sig <- promoter_gene_body_sig_effect_modified_linear_phase_replicate %>%
  subset(p_boostrap_test<=0.05)
promoter_gene_body_modified_linear_phase_replicate_sig <- promoter_gene_body_modified_linear_phase_replicate_sig %>%
  inner_join(gene_symbol_id, by="symbol", relationship = "many-to-many")
promoter_gene_body_modified_linear_phase_replicate_sig_id <- as.data.frame(unique(promoter_gene_body_modified_linear_phase_replicate_sig$id))


promoter_gene_body_linear_phase_replicate_summary <- promoter_gene_body_sig_effect_modified_linear_phase_replicate %>%
  group_by(region, modified_code, expression_effect) %>%
  summarise(sum_effect_poistion = n(), .groups="drop")

promoter_gene_body_linear_phase_replicate_summary_adjust <- summary_adjust(promoter_gene_body_linear_phase_replicate_summary)
promoter_gene_body_linear_phase_replicate_summary_adjust$expression_effect <- factor(promoter_gene_body_linear_phase_replicate_summary_adjust$expression_effect, levels = c("positive", "negative", "none"))

#############################################################################
##### visualize the result
ggplot(promoter_gene_body_linear_phase_replicate_summary_adjust, aes(x=modified_code, y=percentage)) +
  facet_grid(vars(region), scales = "free_y") +
  geom_col(size=0.7, width =0.7, alpha=0.8, aes(color=expression_effect, fill = expression_effect), position = position_dodge(width = 0.72)) +
  scale_color_manual("Gene expression effect", breaks = c("negative", "positive", "none"),
                     values = c("#2b8cbe", "#e25417", "#bdbdbd")) +
  scale_fill_manual("Gene expression effect", breaks = c("negative", "positive", "none"),
                    values = c("#2b8cbe", "#e25417", "#bdbdbd")) +
  labs(y= "Proportion of differentially methylated site") +
  scale_y_continuous(trans = "log1p", limits = c(0, NA),
                     breaks = c(0, 1, 10, 100),
                     labels = c(0, 1, 10, 100)) +
  theme_light() +
  theme(strip.background = element_blank(),
        strip.text = element_text(colour = "black"),
        axis.title = element_text(face = "bold"),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(face="bold"),
        text = element_text(size = 20))
