library(data.table)
library(ggplot2)
library(tidyverse)
library(reshape2)
library(ggfortify)

#############################################################################
### file reading
### these are the files generated by modkit pileup
setwd("")
lacidophilus_m4C_position <- fread("lacidophilus_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
lacidophilus_m5C_position <- fread("lacidophilus_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
lacidophilus_m6A_position <- fread("lacidophilus_primary_pileup_combine_motif_m6a.bed",sep="\t", header=TRUE)

ecoli_m4C_position <- fread("ecoli_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
ecoli_m5C_position <- fread("ecoli_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
ecoli_m6A_position <- fread("ecoli_primary_pileup_combine_m6a.bed",sep="\t", header=TRUE)
options(scipen=999)

#############################################################################
### file clean up
lacidophilus_m5C_position_filter <- lacidophilus_m5C_position[lacidophilus_m5C_position$modified_base_code=="m",]
lacidophilus_m4C_position_filter <- lacidophilus_m4C_position[lacidophilus_m4C_position$modified_base_code=="21839",]
lacidophilus_m6A_position_filter <- lacidophilus_m6A_position[lacidophilus_m6A_position$modified_base_code=="a",]

ecoli_m5C_position_filter <- ecoli_m5C_position[ecoli_m5C_position$modified_base_code=="m",]
ecoli_m4C_position_filter <- ecoli_m4C_position[ecoli_m4C_position$modified_base_code=="21839",]
ecoli_m6A_position_filter <- ecoli_m6A_position[ecoli_m6A_position$modified_base_code=="a",]

ecoli_4mC_5mC_6mA_position_combine <- rbind(ecoli_m5C_position_filter, ecoli_m4C_position_filter, ecoli_m6A_position_filter) %>%
  subset(valid_coverage>=20) %>%
  mutate(genus="Escherichia")

lacidophilus_4mC_5mC_6mA_position_combine <- rbind(lacidophilus_m5C_position_filter, lacidophilus_m4C_position_filter, lacidophilus_m6A_position_filter) %>%
  subset(valid_coverage>=20) %>%
  mutate(genus="Lactobacillus")

setDT(ecoli_4mC_5mC_6mA_position_combine)
setDT(lacidophilus_4mC_5mC_6mA_position_combine)

#############################################################################
### functions to generate DNA methylation matrix for PCA
summary_table <- function(combine_table){
  combine_summary <- combine_table[, .(mean_modified_number = mean(modified_number),
                                       mean_modified_fraction = mean(modified_number/valid_coverage)), 
                                   by = .(genus, chrom, start, end, modified_base_code, strand, phase, replicate)]
  combine_summary <- as.data.frame(combine_summary)
  combine_summary$specific_id <- paste(combine_summary$chrom, combine_summary$end, combine_summary$strand, combine_summary$modified_base_code, sep="_")
  combine_summary <- combine_summary %>%
    mutate(biological_replicate=paste0("replicate_", str_extract(replicate, "\\d+$")))
  return(combine_summary)
}

summary_table_wider <- function(combine_summary){
  combine_summary_wider <- combine_summary %>%
    pivot_wider(names_from = specific_id, values_from = mean_modified_fraction, id_cols = c(replicate, phase, biological_replicate))
  ### add row names and convert dataframe to matrix to accelerate the calculation
  combine_summary_wider <- as.data.frame(combine_summary_wider)
  
  return(combine_summary_wider)
}

summary_cor_table_na_remove <- function(combine_summary_wider){
  combine_summary_cor_table <- combine_summary_wider[, !(names(combine_summary_wider) %in% c("phase", "replicate", "biological_replicate"))]
  combine_summary_cor_table <- as.matrix(combine_summary_cor_table)
  combine_summary_cor_table <- as.data.frame(combine_summary_cor_table)
  combine_summary_cor_table_clean <- Filter(function(x) all(!is.na(x)), combine_summary_cor_table)
  combine_summary_cor_table_clean_numeric <- as.data.frame(lapply(combine_summary_cor_table_clean, function(x) as.numeric(as.character(x))))
  names(combine_summary_cor_table_clean_numeric) <- names(combine_summary_cor_table_clean)
  return(combine_summary_cor_table_clean_numeric)
}

removeZeroVar2 <- function(df){
  # Convert all columns to numeric
  df_numeric <- as.data.frame(lapply(df, function(x) as.numeric(as.character(x))))
  df_numeric <- df_numeric[, sapply(df_numeric, function(x) length(unique(x[!is.na(x)])) > 1)]
  return(df_numeric)
}

summary_wider_clean <- function(combine_summary_wider, summary_cor_table_clean){
  phase_replicate_id <- combine_summary_wider[, (names(combine_summary_wider) %in% c("phase", "replicate", "biological_replicate")), drop = FALSE]
  combine_summary_wider_clean <- cbind(phase_replicate_id, summary_cor_table_clean)
}

#############################################################################
### execute functions to generate DNA methylation matrix for PCA
ecoli_4mC_5mC_6mA_position_combine_summary <- summary_table(ecoli_4mC_5mC_6mA_position_combine)
ecoli_4mC_5mC_6mA_position_combine_summary_table_wider <- summary_table_wider(ecoli_4mC_5mC_6mA_position_combine_summary)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table <- summary_cor_table_na_remove(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider)
ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean <- removeZeroVar2(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table)
ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean <- summary_wider_clean(ecoli_4mC_5mC_6mA_position_combine_summary_table_wider, ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean)
ecoli_methyl_pca_res <- prcomp(ecoli_4mC_5mC_6mA_position_combine_summary_cor_table_clean, scale. = T)

lacidophilus_4mC_5mC_6mA_position_combine_summary <- summary_table(lacidophilus_4mC_5mC_6mA_position_combine)
lacidophilus_4mC_5mC_6mA_position_combine_summary_table_wider <- summary_table_wider(lacidophilus_4mC_5mC_6mA_position_combine_summary)
lacidophilus_4mC_5mC_6mA_position_combine_summary_cor_table <- summary_cor_table_na_remove(lacidophilus_4mC_5mC_6mA_position_combine_summary_table_wider)
lacidophilus_4mC_5mC_6mA_position_combine_summary_cor_table_clean <- removeZeroVar2(lacidophilus_4mC_5mC_6mA_position_combine_summary_cor_table)
lacidophilus_4mC_5mC_6mA_position_combine_summary_wider_clean <- summary_wider_clean(lacidophilus_4mC_5mC_6mA_position_combine_summary_table_wider, lacidophilus_4mC_5mC_6mA_position_combine_summary_cor_table_clean)
lacidophilus_methyl_pca_res <- prcomp(lacidophilus_4mC_5mC_6mA_position_combine_summary_cor_table_clean, scale. = T)

#############################################################################
### visualize the DNA methylation variation
autoplot(ecoli_methyl_pca_res, 
         x = 1, y = 2,
         data=ecoli_4mC_5mC_6mA_position_combine_summary_wider_clean, 
         colour = "phase", size=5, shape = "biological_replicate") +
  scale_color_manual("Phase", breaks = c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) + 
  labs(shape="Biological replicate") + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

autoplot(lacidophilus_methyl_pca_res, 
         x = 1, y = 2,
         data=lacidophilus_4mC_5mC_6mA_position_combine_summary_wider_clean, 
         colour = "phase", size=5, shape = "biological_replicate") +
  scale_color_manual("Phase", breaks = c("exponential", "stationary"),
                     values = c("#444574", "#cd534cff")) + 
  labs(shape="Biological replicate") + 
  theme_light() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 22))