library(data.table)
library(ggplot2)
library(tidyverse)
library(rstatix)
library(ggpubr)

#############################################################################
### file reading
### these are the files generated by modkit pileup
setwd("")
lacidophilus_m4C_position <- fread("lacidophilus_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
lacidophilus_m5C_position <- fread("lacidophilus_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
lacidophilus_m6A_position <- fread("lacidophilus_primary_pileup_combine_motif_m6a.bed",sep="\t", header=TRUE)

ecoli_m4C_position <- fread("ecoli_primary_pileup_combine_m4c.bed",sep="\t", header=TRUE)
ecoli_m5C_position <- fread("ecoli_primary_pileup_combine_m5c.bed",sep="\t", header=TRUE)
ecoli_m6A_position <- fread("ecoli_primary_pileup_combine_m6a.bed",sep="\t", header=TRUE)
options(scipen=999)

### these are the sliding window files generated by bedtools
ecoli_genome_slide <- fread("GCF_000008865.2_ASM886v2_windows_10kb.bed", sep="\t", header = F)
colnames(ecoli_genome_slide) <- c("chromosome", "start", "end")

lacidophilus_genome_slide <- fread("GCF_034298135.1_ASM3429813v1_windows_10kb.bed", sep="\t", header = F)
colnames(lacidophilus_genome_slide) <- c("chromosome", "start", "end")


#############################################################################
#### functions for calculating the modified fraction in each sliding window
windows_methyl_form <- function(genome_slide_bed, filter_pileup_file) {
  fraction_modified_windows <- as.data.frame(matrix(nrow=0, ncol = 9))
  colnames(fraction_modified_windows) <- c("chrom", "start", "end", "modified_base_code", "phase", "replicate",
                                           "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  
  replicate_name_list <- unique(filter_pileup_file$replicate)
  inter_addition_form <- as.data.frame(matrix(nrow=0, ncol = 9))
  colnames(inter_addition_form) <- c("chrom", "start", "end", "modified_base_code","phase", "replicate",
                                     "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  inter_addition_form_final <- as.data.frame(matrix(nrow=0, ncol = 9))
  colnames(inter_addition_form_final) <- c("chrom", "start", "end", "phase", "modified_base_code","replicate",
                                           "sum_valid_coverage", "sum_modified_number", "fraction_modified")
  
  n_iter <- length(seq_len(nrow(genome_slide_bed)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(genome_slide_bed))){
    start_label <- as.integer(genome_slide_bed[i, "start"])
    end_label <- as.integer(genome_slide_bed[i, "end"])
    chromosome <- as.character(genome_slide_bed[i, "chromosome"])
    modified_base_code <- as.character(unique(filter_pileup_file$modified_base_code))
    
    inter_form <- subset(filter_pileup_file,
                         filter_pileup_file$start >= start_label & filter_pileup_file$end < end_label & filter_pileup_file$chrom == chromosome)
    
    inter_form_summary <- inter_form %>%
      group_by(chrom, modified_base_code,phase, replicate) %>%
      summarise(sum_valid_coverage = sum(valid_coverage),
                sum_modified_number = sum(modified_number), .groups = "drop")
    inter_form_summary <- inter_form_summary %>%
      mutate(fraction_modified = 100*sum_modified_number/sum_valid_coverage)
    
    inter_form_summary$start <- start_label
    inter_form_summary$end <- end_label
    
    fraction_modified_windows <- rbind(fraction_modified_windows, inter_form_summary)
    
    setTxtProgressBar(pb, i)
  }
  cat("\n almost there")
  close(pb) # Close the connection
  return(fraction_modified_windows)
}

### functions for filtering regions with the same replicate
common_replicate <- function(position_filter) {
  position_filter$replicate <- sub("lacidophilus_exp|lacidophilus_sta", "replicate", position_filter$replicate)
  position_filter <- position_filter %>%
    mutate(replicate_start_end=paste(replicate, chrom, start, end, sep="_"))
  
  exp_replicate <- unique(position_filter[position_filter$phase=="exponential",]$replicate_start_end)
  sta_replicate <- unique(position_filter[position_filter$phase=="stationary",]$replicate_start_end)
  
  common_replicates <- intersect(exp_replicate, sta_replicate)
  
  position_filter_common <- position_filter %>%
    filter(replicate_start_end %in% common_replicates)
  
  return(position_filter_common)
}

#############################################################################
### file clean up
## lacidophilus
lacidophilus_m5C_position_filter <- lacidophilus_m5C_position[lacidophilus_m5C_position$modified_base_code=="m",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

lacidophilus_m4C_position_filter <- lacidophilus_m4C_position[lacidophilus_m4C_position$modified_base_code=="21839",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

lacidophilus_m6A_position_filter <- lacidophilus_m6A_position[lacidophilus_m6A_position$modified_base_code=="a",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

## ecoli
ecoli_m5C_position_filter <- ecoli_m5C_position[ecoli_m5C_position$modified_base_code=="m",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

ecoli_m4C_position_filter <- ecoli_m4C_position[ecoli_m4C_position$modified_base_code=="21839",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

ecoli_m6A_position_filter <- ecoli_m6A_position[ecoli_m6A_position$modified_base_code=="a",] %>%
  group_by(chrom, start, end, modified_base_code, strand, phase, replicate) %>%
  mutate(fraction_modified = modified_number/valid_coverage) %>%
  subset(valid_coverage>=20)

#############################################################################
### calculate the dna methylation level at each sliding window
## lacidophilus
lacidophilus_m4c_sliding_windows <- windows_methyl_form(lacidophilus_genome_slide, lacidophilus_m4C_position_filter)
lacidophilus_m5c_sliding_windows <- windows_methyl_form(lacidophilus_genome_slide, lacidophilus_m5C_position_filter)
lacidophilus_m6a_sliding_windows <- windows_methyl_form(lacidophilus_genome_slide, lacidophilus_m6A_position_filter)

lacidophilus_m4c_sliding_windows$modified_base_code[lacidophilus_m4c_sliding_windows$modified_base_code=="21839"] <- "m4C"
lacidophilus_m5c_sliding_windows$modified_base_code[lacidophilus_m5c_sliding_windows$modified_base_code=="m"] <- "m5C"
lacidophilus_m6a_sliding_windows$modified_base_code[lacidophilus_m6a_sliding_windows$modified_base_code=="a"] <- "m6A"

lacidophilus_m4c_sliding_windows_common <- common_replicate(lacidophilus_m4c_sliding_windows)
lacidophilus_m5c_sliding_windows_common <- common_replicate(lacidophilus_m5c_sliding_windows)
lacidophilus_m6a_sliding_windows_common <- common_replicate(lacidophilus_m6a_sliding_windows)

lacidophilus_m6a_m4c_m5c_sliding_windows_combine <- rbind(lacidophilus_m4c_sliding_windows_common, 
                                                          lacidophilus_m5c_sliding_windows_common, 
                                                          lacidophilus_m6a_sliding_windows_common) %>%
  mutate(genus="Lactobacillus")

## ecoli
ecoli_m4c_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m4C_position_filter)
ecoli_m5c_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m5C_position_filter)
ecoli_m6a_sliding_windows <- windows_methyl_form(ecoli_genome_slide, ecoli_m6A_position_filter)

ecoli_m4c_sliding_windows$modified_base_code[ecoli_m4c_sliding_windows$modified_base_code=="21839"] <- "m4C"
ecoli_m5c_sliding_windows$modified_base_code[ecoli_m5c_sliding_windows$modified_base_code=="m"] <- "m5C"
ecoli_m6a_sliding_windows$modified_base_code[ecoli_m6a_sliding_windows$modified_base_code=="a"] <- "m6A"

ecoli_m4c_sliding_windows_common <- common_replicate(ecoli_m4c_sliding_windows)
ecoli_m5c_sliding_windows_common <- common_replicate(ecoli_m5c_sliding_windows)
ecoli_m6a_sliding_windows_common <- common_replicate(ecoli_m6a_sliding_windows)

ecoli_m6a_m4c_m5c_sliding_windows_combine <- rbind(ecoli_m4c_sliding_windows_common, 
                                                   ecoli_m5c_sliding_windows_common, 
                                                   ecoli_m6a_sliding_windows_common) %>%
  subset(valid_coverage>=20) %>%
  mutate(genus="Escherichia")

m6a_m4c_m5c_sliding_windows_combine <- rbind(ecoli_m6a_m4c_m5c_sliding_windows_combine, lacidophilus_m6a_m4c_m5c_sliding_windows_combine)

#############################################################################
### statistics of window data
m4c_m5c_sliding_windows_combine_summary <- m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(modified_base_code, phase, genus) %>%
  summarise(mean_fraction_modified = mean(fraction_modified),
            sd_fraction_modified = sd(fraction_modified), 
            mean_modified_number=mean(sum_modified_number), 
            sd_modified_number=sd(sum_modified_number), .groups = "drop")

fraction_modified_windows_compare <- m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(modified_base_code, genus) %>%
  t_test(data = ., fraction_modified ~ phase, paired = T) %>%
  add_significance() %>%
  add_xy_position(x="modified_base_code", dodge = 0.8)

fraction_modified_windows_modified_base_compare <- m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(genus) %>%
  t_test(data = ., fraction_modified ~ modified_base_code, paired = F) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  add_xy_position(x="modified_base_code")
  

fraction_modified_windows_modified_base_phase_compare <- m6a_m4c_m5c_sliding_windows_combine %>%
  group_by(genus, phase) %>%
  t_test(data = ., fraction_modified ~ modified_base_code, paired = F) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  add_xy_position(x="modified_base_code")
  
#############################################################################
### visualize sliding window dna methylation levels
## ecoli
ggplot(m6a_m4c_m5c_sliding_windows_combine[m6a_m4c_m5c_sliding_windows_combine$genus=="Escherichia",], aes(x=modified_base_code,y=fraction_modified)) +
  geom_boxplot(aes(fill=phase), alpha=0.8) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  scale_y_continuous(limits = c(0, NA),
                     breaks = c(0, 1, 4, 10, 30),
                     labels = c(0, 1, 4, 10, 30)) +
  stat_pvalue_manual(fraction_modified_windows_compare[fraction_modified_windows_compare$genus=="Escherichia",], hide.ns = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1) +
  stat_pvalue_manual(fraction_modified_windows_modified_base_compare[fraction_modified_windows_modified_base_compare$genus=="Escherichia",], hide.ns = TRUE,
                     label = "{p.adj.signif}", size=9, bracket.size=1) +
  coord_trans(y="log1p") +
  labs(y="Modified fraction (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

## lacidophilus
ggplot(m6a_m4c_m5c_sliding_windows_combine[m6a_m4c_m5c_sliding_windows_combine$genus=="Lactobacillus",], aes(x=modified_base_code,y=fraction_modified)) +
  geom_boxplot(aes(fill=phase), alpha=0.8) +
  scale_fill_manual("Phase", breaks=c("exponential", "stationary"),
                    values = c("#444574", "#cd534cff")) +
  scale_y_continuous(limits = c(0, NA),
                     breaks = c(0, 1, 4, 10, 30),
                     labels = c(0, 1, 4, 10, 30)) +
  stat_pvalue_manual(fraction_modified_windows_compare[fraction_modified_windows_compare$genus=="Lactobacillus",], hide.ns = TRUE,
                     label = "{p.signif}", size=9, bracket.size=1) +
  stat_pvalue_manual(fraction_modified_windows_modified_base_compare[fraction_modified_windows_modified_base_compare$genus=="Lactobacillus",], hide.ns = TRUE,
                     label = "{p.adj.signif}", size=9, bracket.size=1) +
  coord_trans(y="log1p") +
  labs(y="Modified fraction (%)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 24),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        strip.background = element_blank())

#############################################################################
### examine the dna methylation variation around oriC and ter
m6a_m4c_m5c_sliding_windows_combine_chrom <- m6a_m4c_m5c_sliding_windows_combine[m6a_m4c_m5c_sliding_windows_combine$chrom=="NC_002695.2" | m6a_m4c_m5c_sliding_windows_combine$chrom=="NZ_CP139575.1",]
ecoli_ter_middle <- (2115426+2115454)/2
lacidophilus_ter_middle <- 759661

ecoli_origin_middle <- (4719203+4179580)/2

lacidophilus_origin_1_middle <- (1644596+1645071)/2
lacidophilus_origin_2_middle <- (1646440+1646616)/2

m6a_m4c_m5c_sliding_windows_combine_chrom$replicate <- sub("_exp|_sta", "", m6a_m4c_m5c_sliding_windows_combine_chrom$replicate)

m6a_m4c_m5c_sliding_windows_combine_chrom$replicate <- factor(m6a_m4c_m5c_sliding_windows_combine_chrom$replicate)

m6a_m4c_m5c_sliding_windows_combine_chrom <- as.data.frame(m6a_m4c_m5c_sliding_windows_combine_chrom)

m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider <- m6a_m4c_m5c_sliding_windows_combine_chrom %>%
  select(-sum_valid_coverage, -sum_modified_number) %>%
  pivot_wider(names_from = phase, values_from = fraction_modified) %>%
  mutate(differential_fraction_modified=(stationary+1)/(exponential+1),
         log2_differential_fraction_modified=log2((stationary+1)/(exponential+1)))


m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider_summary <- m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider %>%
  group_by(genus, modified_base_code, chrom, start, end) %>%
  summarize(mean_differential_fraction_modified = mean(log2(differential_fraction_modified)), 
            sd_differential_fraction_modified = sd(log2(differential_fraction_modified)), 
            mean_log2_differential_fraction_modified=mean(log2_differential_fraction_modified), 
            sd_log2_differential_fraction_modified=sd(log2_differential_fraction_modified), .groups = "drop") %>%
  mutate(rel_position_ter=ifelse(genus=="Escherichia", ((start+end)/2)-ecoli_ter_middle, ((start+end)/2)-lacidophilus_ter_middle),
         rel_position_origin_1=ifelse(genus=="Escherichia", ((start+end)/2)-ecoli_origin_middle, ((start+end)/2)-lacidophilus_origin_1_middle),
         rel_position_origin_2=ifelse(genus=="Escherichia", ((start+end)/2)-ecoli_origin_middle, ((start+end)/2)-lacidophilus_origin_2_middle),
         position_middle=(start+end)/2) %>%
  mutate(direction_ter=ifelse(rel_position_ter>=0, "upstream", "downstream"),
         direction_rel_position_origin_1=ifelse(rel_position_origin_1>=0, "upstream", "downstream"),
         direction_rel_position_origin_2=ifelse(rel_position_origin_2>=0, "upstream", "downstream"))

#############################################################################
### visualize the dna methylation variation around oriC and ter
## ecoli
ggplot(m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider_summary[m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider_summary$genus=="Escherichia",], aes(x=end, y=mean_log2_differential_fraction_modified, color=modified_base_code, fill=modified_base_code, grp.label = modified_base_code)) +
  facet_grid(vars(modified_base_code)) +
  geom_point(size=1, alpha=0.7) +
  scale_fill_manual("Modified forms", breaks = c("m6A", "m4C", "m5C"),
                    values = c("#2b8cbe", "#f1a226", "#e25417")) +
  scale_color_manual("Modified forms", breaks = c("m6A", "m4C", "m5C"),
                     values = c("#2b8cbe", "#f1a226", "#e25417")) +
  geom_vline(aes(xintercept=ecoli_origin_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=ecoli_origin_middle+170000, y=2.0, label="oriC", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=ecoli_ter_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=ecoli_ter_middle+150000, y=2.0, label="ter", size=6, color = "#1d1a2f") +
  theme_bw() +
  labs(x="Genomic position (bp)", y="Log2 modified fraction change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 22),
        legend.position = "bottom",
        strip.background = element_rect(fill = NA, color = NA)) +
  guides(colour = guide_legend(override.aes = list(size=4, alpha=0.6)))

## lacidophilus
ggplot(m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider_summary[m6a_m4c_m5c_sliding_windows_combine_chrom_fraction_wider_summary$genus=="Lactobacillus",], aes(x=end, y=mean_log2_differential_fraction_modified, color=modified_base_code, fill=modified_base_code, grp.label = modified_base_code)) +
  facet_grid(vars(modified_base_code)) +
  # stat_cor(method = "spearman", p.accuracy=0.001, size=5, label.y = 0.2) +
  # geom_smooth(method = "lm", linewidth=0.7, se=T) +
  geom_point(size=1, alpha=0.7) +
  scale_fill_manual("Modified forms", breaks = c("m6A", "m4C", "m5C"),
                    values = c("#2b8cbe", "#f1a226", "#e25417")) +
  scale_color_manual("Modified forms", breaks = c("m6A", "m4C", "m5C"),
                     values = c("#2b8cbe", "#f1a226", "#e25417")) +
  geom_vline(aes(xintercept=lacidophilus_origin_1_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_origin_1_middle-60000, y=0.2, label="oriC1", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=lacidophilus_origin_2_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_origin_2_middle+60000, y=0.2, label="oriC2", size=6, color = "#1d1a2f") +
  geom_vline(aes(xintercept=lacidophilus_ter_middle), color = "#1d1a2f", size=0.7) +
  geom_text(x=lacidophilus_ter_middle+60000, y=0.2, label="ter", size=6, color = "#1d1a2f") +
  theme_bw() +
  labs(x="Relative position to DNA replication terminus (bp)", y="Log2 modified fraction change") +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        legend.title = element_text(face = "bold")) +
  theme(text = element_text(size = 22),
        legend.position = "bottom",
        strip.background = element_rect(fill = NA, color = NA)) +
  guides(colour = guide_legend(override.aes = list(size=4, alpha=0.6)))