library(data.table)
library(ggplot2)
library(tidyverse)
library(tidyverse)
library(lmerTest)
library(glue)

#############################################################################
### file reading
### these are the files generated by using sgementing with 10-kb sliding windows
setwd("")
methyl_fraction_wider <- readRDS("ecoli_lacidophilus_chrom_fraction_wider.rds")
seq_depth<- readRDS("ecoli_lacidophilus_seq_depth.rds")

#############################################################################
### put specific marker
seq_depth_longer <- seq_depth %>%
  pivot_longer(col=c("exponential", "stationary"), names_to = "phase", values_to = "seq_depth") %>%
  mutate(replicate_start_end_phase_genus=paste(replicate_id, chrom, start, end, phase, genus, sep = "_"))

methyl_fraction_longer <- methyl_fraction_wider %>%
  pivot_longer(col=c("exponential", "stationary"), names_to = "phase", values_to = "fraction_modified") %>%
  mutate(replicate_start_end_phase_genus=paste(replicate_start_end, phase, genus, sep = "_"))

seq_depth_methyl <- methyl_fraction_longer %>%
  inner_join(seq_depth_longer[,c("replicate_start_end_phase_genus", "seq_depth")], by="replicate_start_end_phase_genus")

#############################################################################
### linear mixed model to evaluate differnt effects on DNA methylation levels
ecoli_origin <- lmer(fraction_modified ~ phase + seq_depth + modified_base_code + (1 | replicate),
                     data = seq_depth_methyl[seq_depth_methyl$genus=="Escherichia",], control=lmerControl(autoscale = TRUE))
ecoli_origin_anova <- as.data.frame(anova(ecoli_origin))
ecoli_origin_anova$term <- rownames(ecoli_origin_anova)
rownames(ecoli_origin_anova) <- NULL


lacidophilus_origin <- lmer(fraction_modified ~ phase + seq_depth + modified_base_code + (1 | replicate),
                            data = seq_depth_methyl[seq_depth_methyl$genus=="Lactobacillus",], control=lmerControl(autoscale = TRUE))
lacidophilus_origin_anova <- as.data.frame(anova(lacidophilus_origin))
lacidophilus_origin_anova$term <- rownames(lacidophilus_origin_anova)
rownames(lacidophilus_origin_anova) <- NULL


```