library(ggplot2)
library(tidyverse)
library(data.table)
library(grid)
library(janitor)

#############################################################################
### file reading
### these are the files generated by dmr R scripts
## ecoli
setwd("")
ecoli_gene_body_promoter_position_differntial <- fread("ecoli_growth_phase_diffferential_metyhl_position_gene.tsv",sep="\t", header=TRUE)
ecoli_nonregulatory_position_differntial <- fread("ecoli_growth_phase_diffferential_metyhl_none_regulatory_position.tsv",sep="\t", header=TRUE)

ecoli_oriC_extend <- fread("ecoli_oriC_extend.bed", header=F)
ecoli_ter_extend <- fread("ecoli_ter_extend.bed", header=F)
ecoli_other_regions_extend <- fread("ecoli_other_regions_extend.bed", header=F)
colnames(ecoli_oriC_extend) <- c("chromosome", "start", "end")
colnames(ecoli_ter_extend) <- c("chromosome", "start", "end")
colnames(ecoli_other_regions_extend) <- c("chromosome", "start", "end")

ecoli_oriC_extend$genomic_feature <- "oriC"
ecoli_ter_extend$genomic_feature <- "ter"
ecoli_other_regions_extend$genomic_feature <- "others"

ecoli_genomic_feature_extend <- rbind(ecoli_oriC_extend, ecoli_ter_extend, ecoli_other_regions_extend)

## lacidophilus
setwd("")
lacidophilus_gene_body_promoter_position_differntial <- fread("lacidophilus_growth_phase_diffferential_metyhl_position_gene.tsv",sep="\t", header=TRUE)
lacidophilus_nonregulatory_position_differntial <- fread("lacidophilus_growth_phase_diffferential_metyhl_none_regulatory_position.tsv",sep="\t", header=TRUE)

lacidophilus_oriC_extend <- fread("lacidophilus_oriC_extend.bed", header=F)
lacidophilus_ter_extend <- fread("lacidophilus_ter_extend.bed", header=F)
lacidophilus_other_regions_extend <- fread("lacidophilus_other_regions_extend.bed", header=F)

colnames(lacidophilus_oriC_extend) <- c("chromosome", "start", "end")
colnames(lacidophilus_ter_extend) <- c("chromosome", "start", "end")
colnames(lacidophilus_other_regions_extend) <- c("chromosome", "start", "end")

lacidophilus_oriC_extend$genomic_feature <- "oriC"
lacidophilus_ter_extend$genomic_feature <- "ter"
lacidophilus_other_regions_extend$genomic_feature <- "others"

lacidophilus_genomic_feature_extend <- rbind(lacidophilus_oriC_extend, lacidophilus_ter_extend, lacidophilus_other_regions_extend)


#############################################################################
### functions to inpect position in both gene body and promoter
postition_inspect <- function(table, count_number){
  postition_inspect_list <- list()
  unique_chrom_end_strand_modified_base_code_ids <- unique(table$chrom_end_strand_modified_base_code)
  
  for (ids in unique_chrom_end_strand_modified_base_code_ids) {
    id=ids
    count_id=sum(table$chrom_end_strand_modified_base_code == id)
    if (count_id > count_number){
      postition_inspect_list[[id]] <- count_id
    }else{
      next
    }
  }
  return(postition_inspect_list)
}

#############################################################################
### process analysis for differentially methylation site counting
ecoli_gene_body_promoter_position_differntial$genus <- "Escherichia"
lacidophilus_gene_body_promoter_position_differntial$genus <- "Lactobacillus"

ecoli_nonregulatory_position_differntial$genus <- "Escherichia"
lacidophilus_nonregulatory_position_differntial$genus <- "Lactobacillus"

ecoli_lacidophilus_differntial_combine <- rbind(ecoli_gene_body_promoter_position_differntial, lacidophilus_gene_body_promoter_position_differntial) %>%
  mutate(chrom_end_strand_modified_base_code = paste(genus, chrom, end, strand, modified_base_code, sep = "_"))

ecoli_lacidophilus_differntial_nonregulatory_combine <- rbind(ecoli_nonregulatory_position_differntial, lacidophilus_nonregulatory_position_differntial) %>%
  mutate(chrom_end_strand_modified_base_code = paste(genus, chrom, end, strand, modified_base_code, sep = "_"))

postition_inspect(ecoli_lacidophilus_differntial_nonregulatory_combine,2)

inspect <- postition_inspect(ecoli_lacidophilus_differntial_combine,2)
both_position <- names(inspect)

ecoli_lacidophilus_differntial_combine$region <- ifelse(ecoli_lacidophilus_differntial_combine$chrom_end_strand_modified_base_code %in%both_position,
                                                        "both", ecoli_lacidophilus_differntial_combine$region)

ecoli_lacidophilus_differntial_combine_site_summary <- ecoli_lacidophilus_differntial_combine %>%
  group_by(genus,region,modified_base_code, chrom_end_strand_modified_base_code) %>%
  summarise(overall_mean_modified_fraction=mean(mean_modified_fraction), .groups="drop")

ecoli_lacidophilus_differntial_combine_site_end_summary <- ecoli_lacidophilus_differntial_combine %>%
  group_by(chrom, genus,region,modified_base_code, start, end, chrom_end_strand_modified_base_code) %>%
  summarise(overall_mean_modified_fraction=mean(mean_modified_fraction), .groups="drop")

ecoli_lacidophilus_differntial_combine_gene_summary <- ecoli_lacidophilus_differntial_combine %>%
  group_by(chrom, genus, region, start, end, modified_base_code, symbol, id, chrom_end_strand_modified_base_code) %>%
  summarise(overall_mean_modified_fraction=mean(mean_modified_fraction), .groups="drop")

ecoli_lacidophilus_differntial_nonregulatory_combine_site_summary <- ecoli_lacidophilus_differntial_nonregulatory_combine %>%
  group_by(genus, region, modified_base_code, chrom_end_strand_modified_base_code) %>%
  summarise(overall_mean_modified_fraction=mean(mean_modified_fraction), .groups="drop")

ecoli_gc <- 0.505
ecoli_genome_size <- 5498578+3306+92721

ecoli_gc_bases <- ecoli_genome_size*ecoli_gc
ecoli_at_bases <- ecoli_genome_size*(1-ecoli_gc)

lacidophilus_gc <- 0.345
lacidophilus_genome_size <- 1978847

ecoli_lacidophilus_differntial_combine_site_count <- rbind(ecoli_lacidophilus_differntial_nonregulatory_combine_site_summary, 
                                                           ecoli_lacidophilus_differntial_combine_site_summary) %>%
  group_by(genus,region,modified_base_code) %>%
  summarise(site_count=n(),.groups="drop") %>%
  group_by(genus,modified_base_code) %>%
  mutate(site_count_percentage=100*site_count/sum(site_count))


ecoli_lacidophilus_differntial_combine_site_count <- rbind(ecoli_lacidophilus_differntial_nonregulatory_combine_site_summary, 
                                                           ecoli_lacidophilus_differntial_combine_site_summary) %>%
  group_by(genus,region,modified_base_code) %>%
  summarise(site_count=n(), .groups="drop") %>%
  group_by(genus,modified_base_code) %>%
  mutate(normalize_count=ifelse(genus=="Escherichia" & modified_base_code %in% c("m4C", "m5C"), site_count/ecoli_gc,
                                ifelse(genus=="Escherichia" & modified_base_code %in% c("m6A"), site_count/(1-ecoli_gc), 
                                       ifelse(genus=="Lactobacillus" & modified_base_code %in% c("m4C", "m5C"), site_count/lacidophilus_gc,
                                              site_count/(1-lacidophilus_gc)))),
         site_count_percentage=100*normalize_count/sum(normalize_count))

ecoli_lacidophilus_differntial_combine_site_count$region <- factor(ecoli_lacidophilus_differntial_combine_site_count$region, levels=c("gene_body", "promoter", "both", "neither"))

#############################################################################
### visualization
ggplot(ecoli_lacidophilus_differntial_combine_site_count[ecoli_lacidophilus_differntial_combine_site_count$genus=="Escherichia",], aes(x=modified_base_code, y=normalize_count, fill=region, colour = region)) +
  geom_point(alpha=0.9, size=7, position = position_dodge2(width = 0.6)) +
  geom_linerange(aes(x = modified_base_code, ymin = 0, ymax = normalize_count),
                 alpha=0.9, position = position_dodge2(width = 0.6)) +
  scale_y_continuous(transform = "log1p",
                     limits = c(0, NA),
                     breaks = c(0, 1, 10, 100, 1000, 10000, 10000),
                     labels = c(0, 1, 10, 100, 1000, 10000, 10000)) +
  scale_fill_manual("Genome features", breaks=c("gene_body", "promoter", "both", "neither"),
                    values = c("#7da66a", "#328cb0", "#644b77", "#bababa")) +
  scale_color_manual("Genome features", breaks=c("gene_body", "promoter", "both", "neither"),
                     values = c("#7da66a", "#328cb0", "#644b77", "#bababa")) +
  theme_light() +
  labs(y="Normalized differentially methylated sites") +
  theme(strip.background = element_blank(),
        strip.text = element_text(colour = "black"),
        axis.title = element_text(face = "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face="bold", hjust = -1),
        legend.position = "bottom",
        legend.title = element_text(face="bold"),
        text = element_text(size = 23.5))

ggplot(ecoli_lacidophilus_differntial_combine_site_count[ecoli_lacidophilus_differntial_combine_site_count$genus=="Lactobacillus",], aes(x=modified_base_code, y=normalize_count, fill=region, colour = region)) +
  geom_point(alpha=0.9, size=7, position = position_dodge2(width = 0.6)) +
  geom_linerange(aes(x = modified_base_code, ymin = 0, ymax = normalize_count),
                 alpha=0.9, position = position_dodge2(width = 0.6)) +
  scale_y_continuous(transform = "log1p",
                     limits = c(0, 1000),
                     breaks = c(0, 1, 10, 100, 1000),
                     labels = c(0, 1, 10, 100, 1000)) +
  scale_fill_manual("Genome features", breaks=c("gene_body", "promoter", "both", "neither"),
                    values = c("#7da66a", "#328cb0", "#644b77", "#bababa")) +
  scale_color_manual("Genome features", breaks=c("gene_body", "promoter", "both", "neither"),
                     values = c("#7da66a", "#328cb0", "#644b77", "#bababa")) +
  theme_light() +
  labs(y="Normolized differentially methylated sites") +
  theme(strip.background = element_blank(),
        strip.text = element_text(colour = "black"),
        axis.title = element_text(face = "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face="bold"),
        legend.position = "bottom",
        legend.title = element_text(face="bold"),
        text = element_text(size = 23.5))

