library(ggplot2)
library(tidyverse)
library(data.table)
library(DESeq2)

#############################################################################
#### file reading
#### these are the files generated by htseq
setwd("")
options(scipen=999)

#### Set the prefix for each output file name
outputPrefix <- "ecoli_DESeq2"

#### import htseq count files and define conditions
sampleFiles<- c("EE_1_gene_counts.tsv",
                "EE_2_gene_counts.tsv",
                "EE_3_gene_counts.tsv",
                "ES_1_gene_counts.tsv",
                "ES_2_gene_counts.tsv",
                "ES_3_gene_counts.tsv")
sampleNames <- c("exp_replicate_1","exp_replicate_2","exp_replicate_3","sta_replicate_1","sta_replicate_2","sta_replicate_3")
replicate_id <- c("replicate_1","replicate_2","replicate_3","replicate_1","replicate_2","replicate_3")
sampleCondition <- c("exponential","exponential","exponential","stationary","stationary","stationary")

sampleTable <- data.frame(sampleName = sampleNames, 
                          fileName = sampleFiles, 
                          replicate_id = replicate_id,
                          condition = sampleCondition)
sampleTable$condition <- factor(sampleTable$condition)
sampleTable$replicate_id <- factor(sampleTable$replicate_id)
treatments = c("exponential","stationary")

#### build the DESeqDataSet
ddsHTSeq <- DESeqDataSetFromHTSeqCount(sampleTable = sampleTable,
                                       directory = "",
                                       design = ~ condition)

#############################################################################
#### perform initial differential expression
dds <- DESeq(ddsHTSeq)
dds$condition <- factor(dds$condition, levels = c("exponential","stationary"))
dds

#### perform log2 scale transformation with normalization
vsd <- vst(dds, blind=FALSE)
vst_data <- as.data.frame(assay(vsd))
vst_data$id <- rownames(vst_data)
rownames(vst_data) <- NULL

rld <- rlog(dds, blind=FALSE)
rld_data <- as.data.frame(assay(rld))
rld_data$id <- rownames(rld_data)
rownames(rld_data) <- NULL

####
deseq_results <- results(dds, alpha=0.05)
sum(deseq_results$padj < 0.05, na.rm=TRUE)

#### reorder base on p-value
deseq_results_ordered <- deseq_results[order(deseq_results$pvalue),]
deseq_results_ordered_id <- deseq_results_ordered
deseq_results_ordered_id <- as.data.frame(deseq_results_ordered_id)
deseq_results_ordered_id$id <- rownames(deseq_results_ordered_id)
rownames(deseq_results_ordered_id) <- NULL

deseq_results_ordered_sig <- subset(deseq_results_ordered_id, padj < 0.05)
deseq_results_ordered_sig_upregulate <- subset(deseq_results_ordered_id, padj < 0.05 & log2FoldChange > 0)
deseq_results_ordered_sig_downregulate <- subset(deseq_results_ordered_id, padj < 0.05 & log2FoldChange < 0)

