library(ggplot2)
library(tidyverse)
library(data.table)
library(grid)
library(ggvenn)
library(janitor)
library(glue)
library(ggVennDiagram)
library(patchwork)


#############################################################################
### file reading
### these are the files generated by modkit pileup or dmr
setwd("")
ecoli_position <- fread("ecoli_pileup_motif_focus_combine.bed",sep="\t", header=TRUE)
lacidophilus_position <- fread("lacidophilus_pileup_motif_focus_combine.bed",sep="\t", header=TRUE)

ecoli_dmr_methyl_phase_4mC <- fread("ecoli_exp_sta_dmr_motif_gatcntc.tsv",sep="\t", header=TRUE)
ecoli_dmr_methyl_phase_5mC <- fread("ecoli_exp_sta_dmr_motif_ccwgg.tsv",sep="\t", header=TRUE)
ecoli_dmr_methyl_phase_6mA <- fread("ecoli_exp_sta_dmr_motif_gatc.tsv",sep="\t", header=TRUE)

lacidophilus_dmr_methyl_phase_6mA <- fread("lacidophilus_exp_sta_dmr_motif_gcatc.tsv",sep="\t", header=TRUE)

ecoli_mRNA_promoter <- fread("GCF_000008865.2_ASM886v2_genomic_gene_extended_promoter.tsv", sep="\t", header = F)
ecoli_gene_body <- fread("GCF_000008865.2_ASM886v2_genomic_gene.tsv", sep="\t", header = F)
ecoli_nonregulate <- fread("GCF_000008865.2_ASM886v2_genomic_nonregulatory.bed", sep="\t", header = F)

lacidophilus_mRNA_promoter <- fread("GCF_034298135.1_ASM3429813v1_genomic_gene_extended_promoter.tsv", sep="\t", header = F)
lacidophilus_gene_body <- fread("GCF_034298135.1_ASM3429813v1_genomic_gene.tsv", sep="\t", header = F)
lacidophilus_nonregulate <- fread("GCF_034298135.1_ASM3429813v1_genomic_nonregulatory.bed", sep="\t", header = F)

colnames(ecoli_mRNA_promoter) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")
colnames(ecoli_gene_body) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")
colnames(ecoli_nonregulate) <- c("seqname", "start", "end")

colnames(lacidophilus_mRNA_promoter) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")
colnames(lacidophilus_gene_body) <- c("seqname", "feature", "start", "end", "strand", "id", "locus_tag", "symbol")
colnames(lacidophilus_nonregulate) <- c("seqname", "start", "end")

options(scipen=999)

#############################################################################
### functions for analysis
### a function a clean up uncertain strand direction position
position_clean <- function(pileup_position_filter, dmr_tsv_file) {
  position_file <- pileup_position_filter %>%
    mutate(specific_id_strand = paste(pileup_position_filter$chrom,pileup_position_filter$end, pileup_position_filter$strand, sep = "_"),
           specific_id = paste(pileup_position_filter$chrom, pileup_position_filter$end, sep = "_")) %>%
    select(specific_id_strand, specific_id, strand)
  
  position_file_tidy <- position_file[!duplicated(position_file$specific_id_strand), ]
  position_file_tidy_vec <- sub("_[+-]$", "", position_file_tidy$specific_id_strand)
  
  duplicate_id <- position_file_tidy_vec[duplicated(position_file_tidy_vec)]
  print(duplicate_id)
  position_file_tidy_clean <- position_file_tidy %>%
    filter(!(specific_id %in% duplicate_id))
  
  dmr_tsv_file <- dmr_tsv_file %>%
    mutate(specific_id = paste(dmr_tsv_file$chrom, dmr_tsv_file$end, sep = "_"))
  
  dmr_tsv_file_clean <- dmr_tsv_file %>%
    filter(!(specific_id %in% duplicate_id))
  
  dmr_tsv_file_clean <- dmr_tsv_file_clean %>%
    inner_join(position_file_tidy_clean, by = join_by(specific_id), keep = F, unmatched = "drop")
  
  unique_end_num <- length(unique(dmr_tsv_file_clean$specific_id))
  # dmr_tsv_file_clean <- dmr_tsv_file_clean %>%
  # mutate(differential=ifelse(balanced_map_pvalue <= 0.05/unique_end_num, "yes", "no"))
  dmr_tsv_file_clean <- dmr_tsv_file_clean %>%
    mutate(differential=ifelse(balanced_map_pvalue <= 0.05, "yes", "no"))
  
  return(dmr_tsv_file_clean)
}

#### a function to change the comparison group name in the dmr file
group_name_change <- function(dmr_tsv_file_clean, a_group_name, b_group_name) {
  names(dmr_tsv_file_clean) <- gsub("^a_", paste0(a_group_name, "_", sep=""), colnames(dmr_tsv_file_clean))
  names(dmr_tsv_file_clean) <- gsub("^b_", paste0(b_group_name, "_", sep=""), colnames(dmr_tsv_file_clean))
  
  names(dmr_tsv_file_clean) <- gsub("_a_", paste0("_", a_group_name, "_", sep=""), colnames(dmr_tsv_file_clean))
  names(dmr_tsv_file_clean) <- gsub("_b_", paste0("_", b_group_name, "_", sep=""), colnames(dmr_tsv_file_clean))
  
  return(dmr_tsv_file_clean)
}

#### functions to combine methylated sites and genes
deferential_methylated_form <- function(dmr_methyl_position, gff_tsv){
  differential_methyl_from <- as.data.frame(matrix(ncol = length(c(names(dmr_methyl_position), "id", "locus_tag", "symbol")), nrow = 0))
  
  colnames(differential_methyl_from) <- c(names(dmr_methyl_position), "id", "locus_tag", "symbol")
  
  n_iter <- length(seq_len(nrow(gff_tsv)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(gff_tsv))){
    
    seqname <- as.character(gff_tsv[i,"seqname"])
    gff_start <- as.integer(gff_tsv[i,"start"])
    gff_end <- as.integer(gff_tsv[i,"end"])
    gff_strand <- as.character(gff_tsv[i,"strand"])
    gff_id <- as.character(gff_tsv[i,"id"])
    gff_locus <- as.character(gff_tsv[i,"locus_tag"])
    gff_symbol <- as.character(gff_tsv[i,"symbol"])
    
    inter_form <- subset(dmr_methyl_position,
                         dmr_methyl_position$chrom == seqname & dmr_methyl_position$end >= gff_start & dmr_methyl_position$strand == gff_strand &
                           dmr_methyl_position$end <= gff_end)
    
    inter_form$id <- gff_id
    inter_form$locus_tag <- gff_locus
    inter_form$symbol <- gff_symbol
    
    differential_methyl_from <- rbind(differential_methyl_from, inter_form)
    
    setTxtProgressBar(pb, i)
  }
  cat("\n It's all done mate 🍺 ")
  close(pb) # Close the connection
  return(differential_methyl_from)
}

deferential_methylated_form_none_regulatory <- function(dmr_methyl_position, gff_tsv){
  differential_methyl_from <- as.data.frame(matrix(ncol = length(c(names(dmr_methyl_position))), nrow = 0))
  
  colnames(differential_methyl_from) <- c(names(dmr_methyl_position))

  n_iter <- length(seq_len(nrow(gff_tsv)))
  
  pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                       max = n_iter, # Maximum value of the progress bar
                       style = 3,    # Progress bar style (also available style = 1 and style = 2)
                       width = 50,   # Progress bar width. Defaults to getOption("width")
                       char = "=")
  
  for (i in seq_len(nrow(gff_tsv))){
    
    seqname <- as.character(gff_tsv[i,"seqname"])
    gff_start <- as.integer(gff_tsv[i,"start"])
    gff_end <- as.integer(gff_tsv[i,"end"])
    
    inter_form <- subset(dmr_methyl_position,
                         dmr_methyl_position$chrom == seqname & dmr_methyl_position$end > gff_start & dmr_methyl_position$end < gff_end)
    
    differential_methyl_from <- rbind(differential_methyl_from, inter_form)
    
    setTxtProgressBar(pb, i)
  }
  cat("\n It's all done mate 🍺 ")
  close(pb) # Close the connection
  return(differential_methyl_from)
}

#### a function to clean up the differential form with methylated sites and genes
differential_form_clean_up <- function(differential_form) {
  differential_form_clean <- differential_form %>%
    select(chrom, end, exp_pct_modified, sta_pct_modified, symbol)
  
  differential_form_clean <- differential_form_clean %>%
    rename(exponential = exp_pct_modified,
           stationary = sta_pct_modified)
  
  differential_form_clean_longer <- differential_form_clean %>%
    pivot_longer(cols = c("exponential", "stationary"), names_to = "phase", values_to = "modified_percentage")
  
  differential_form_clean_summary <- differential_form_clean_longer %>%
    group_by(chrom, phase, symbol) %>%
    summarize(mean_modified_percentage = mean(modified_percentage), 
              sd_modified_percentage = sd(modified_percentage), .groups= "drop")
  return(differential_form_clean_summary)
}


#### functions to identify differential modified position at each replicate with gene information
differntial_position_replicate <- function(differential_methyl_from, pileup_position, specified_region){
  differ_position_list <- differential_methyl_from %>%
    select(specific_id_strand, id, locus_tag, symbol)
  
  pileup_position <- pileup_position %>%
    mutate(specific_id_strand = paste(chrom, end, strand, sep = "_"))
  
  differential_methyl_region_position_clean <- pileup_position[pileup_position$specific_id_strand %in% differ_position_list$specific_id_strand,]
  
  differential_methyl_region_position <- merge(differ_position_list, differential_methyl_region_position_clean, by = "specific_id_strand", all.x = TRUE)
  
  differential_methyl_region_position_summary <- differential_methyl_region_position %>%
    group_by(chrom, start, end, strand, modified_base_code, phase, id, locus_tag, symbol) %>%
    summarise(mean_modified_fraction = mean(100*modified_number/valid_coverage), 
              sd_modified_fraction = sd(100*modified_number/valid_coverage), 
              region = specified_region, .groups = "drop")
  
  differential_methyl_region_position_summary[, c("start", "end")] <- lapply(differential_methyl_region_position_summary[, c("start", "end")], as.character)
  
  return(differential_methyl_region_position_summary)
}

differntial_position_replicate_none_regulatory <- function(differential_methyl_from, pileup_position, specified_region){
  differ_position_list <- differential_methyl_from %>%
    select(specific_id_strand)
  
  pileup_position <- pileup_position %>%
    mutate(specific_id_strand = paste(chrom, end, strand, sep = "_"))
  
  differential_methyl_region_position_clean <- pileup_position[pileup_position$specific_id_strand %in% differ_position_list$specific_id_strand,]
  
  differential_methyl_region_position <- merge(differ_position_list, differential_methyl_region_position_clean, by = "specific_id_strand", all.x = TRUE)
  
  differential_methyl_region_position_summary <- differential_methyl_region_position %>%
    group_by(chrom, start, end, strand, modified_base_code, phase) %>%
    summarise(mean_modified_fraction = mean(100*modified_number/valid_coverage), 
              sd_modified_fraction = sd(100*modified_number/valid_coverage), 
              region = specified_region, .groups = "drop")
  
  differential_methyl_region_position_summary[, c("start", "end")] <- lapply(differential_methyl_region_position_summary[, c("start", "end")], as.character)
  
  return(differential_methyl_region_position_summary)
}

#### a function to identify differential modified position at each replicate with gene information
differntial_position_replicate <- function(differential_methyl_from, pileup_position, specified_region){
  differ_position_list <- differential_methyl_from %>%
    select(specific_id_strand, id, locus_tag, symbol)
  
  pileup_position <- pileup_position %>%
    mutate(specific_id_strand = paste(chrom, end, strand, sep = "_"))
  
  differential_methyl_region_position_clean <- pileup_position[pileup_position$specific_id_strand %in% differ_position_list$specific_id_strand,]
  
  differential_methyl_region_position <- merge(differ_position_list, differential_methyl_region_position_clean, by = "specific_id_strand", all.x = TRUE)
  
  differential_methyl_region_position_summary <- differential_methyl_region_position %>%
    group_by(chrom, start, end, strand, modified_base_code, phase, id, locus_tag, symbol) %>%
    summarise(mean_modified_fraction = mean(100*modified_number/valid_coverage), 
              sd_modified_fraction = sd(100*modified_number/valid_coverage), 
              region = specified_region, .groups = "drop")
  
  differential_methyl_region_position_summary[, c("start", "end")] <- lapply(differential_methyl_region_position_summary[, c("start", "end")], as.character)
  
  return(differential_methyl_region_position_summary)
}

#### a function to clean up the modified code in the piple up file
position_clean_modified_code <- function(pileup_position, raw_modified_code, clean_modified_code) {
  pileup_position_clean_modified_code <- pileup_position %>%
    filter(modified_base_code == raw_modified_code) %>%
    mutate(modified_base_code = clean_modified_code)
  return(pileup_position_clean_modified_code)
}

#### a function to generate unique gene id
unique_id_generation <- function(position_file){
  position_file <- setDT(position_file)[, c("code","exp_percentage") := tstrsplit(exp_mod_percentages, ":")][, specific_id_strand_code := paste(specific_id_strand, code, sep = "_")]
  return(position_file)
}

#### a function to generate unique gene id list
list_generation <- function(all_position_file, motif_focus_file) {
  position_list <- list()
  
  all_position_list=strsplit(as.vector(unique(all_position_file$specific_id_strand_code)), ",")
  motif_focus_list=strsplit(as.vector(unique(motif_focus_file$specific_id_strand_code)), ",")
  
  position_list[[glue("locus-based")]] <- all_position_list
  position_list[[glue("motif-based")]] <- motif_focus_list
  
  return(position_list)
}

#### a function to generate a venn graph
venn_graphing <- function(list_file, title_name){
  list_file_stack <- stack(list_file)
  
  list_file_stack_wider <- list_file_stack %>%
    pivot_wider(names_from = values, values_from = values, id_cols = ind)
  
  list_file_stack_wider[] <- lapply(list_file_stack_wider, as.character)
  
  list_file_stack_wider_long <- rbind(names(list_file_stack_wider), list_file_stack_wider) %>%
    t() %>%
    row_to_names(row_number = 1) %>%
    as.tibble()
  
  list_file_stack_wider_long[,-1] <- lapply(list_file_stack_wider_long[,-1], function(x) ifelse(is.na(x), FALSE, TRUE))
  
  venn_graph <- ggplot(list_file_stack_wider_long, aes(A=`motif-based`, B=`locus-based`)) +
    geom_venn(set_names = c("motif-based","locus-based"),
              stroke_size = 0.8,
              text_size = 4,
              show_percentage = T,
              fill_alpha = 0.5,
              auto_scale = F,
              fill_color = c("#756bb1", "#CD534CFF")) +
    labs(title = title_name) +
    theme_void() +
    coord_fixed(clip = "off") +
    theme(plot.title = element_text(hjust = 0.5, size=18, face = "bold", vjust = -10))
  
  return(venn_graph)
}

#### a function for fisher exact test
fisher_exact_test <- function(list_file, genome_size) {
  common <- length(intersect(list_file[["motif-based"]], list_file[["locus-based"]]))
  motif_unique <- length(setdiff(list_file[["motif-based"]], list_file[["locus-based"]]))
  locus_unique <- length(setdiff(list_file[["locus-based"]], list_file[["motif-based"]]))
  
  fisher_forms <- matrix(c(common, locus_unique, motif_unique, genome_size-common-locus_unique-motif_unique), nrow = 2)
  
  return_list <- list()
  return_list[[1]] <- fisher_forms
  return_list[[2]] <- fisher.test(fisher_forms, alternative = "greater")
  
  return(return_list)
}

#############################################################################
#### perform analysis using functions
#### perform file cleaning and methylation region tageting only on differential sties on escherichia
ecoli_m4C_position_clean <- position_clean(ecoli_position[ecoli_position$modified_base_code=="21839",], ecoli_dmr_methyl_phase_4mC)
ecoli_m5C_position_clean <- position_clean(ecoli_position[ecoli_position$modified_base_code=="m",], ecoli_dmr_methyl_phase_5mC)
ecoli_m6A_position_clean <- position_clean(ecoli_position[ecoli_position$modified_base_code=="a",], ecoli_dmr_methyl_phase_6mA)

ecoli_m4C_position_clean <- group_name_change(ecoli_m4C_position_clean, "exp", "sta")
ecoli_m5C_position_clean <- group_name_change(ecoli_m5C_position_clean, "exp", "sta")
ecoli_m6A_position_clean <- group_name_change(ecoli_m6A_position_clean, "exp", "sta")

ecoli_m4C_position_clean_differntial <- ecoli_m4C_position_clean[ecoli_m4C_position_clean$differential=="yes",]
ecoli_m5C_position_clean_differntial <- ecoli_m5C_position_clean[ecoli_m5C_position_clean$differential=="yes",]
ecoli_m6A_position_clean_differntial <- ecoli_m6A_position_clean[ecoli_m6A_position_clean$differential=="yes",]

###### m6a
ecoli_promoter_methyl_from_differential_m6A <- deferential_methylated_form(ecoli_m6A_position_clean_differntial, ecoli_mRNA_promoter)
ecoli_gene_body_methyl_from_differential_m6A <- deferential_methylated_form(ecoli_m6A_position_clean_differntial, ecoli_gene_body)

ecoli_promoter_gene_body_differential_m6A <- rbind(ecoli_promoter_methyl_from_differential_m6A, ecoli_gene_body_methyl_from_differential_m6A)
ecoli_promoter_gene_body_differential_m6A_gene_id <- sub("^GeneID:", "", unique(ecoli_promoter_gene_body_differential_m6A$id))

###### m4c
ecoli_promoter_methyl_from_differential_m4C <- deferential_methylated_form(ecoli_m4C_position_clean_differntial, ecoli_mRNA_promoter)
ecoli_gene_body_methyl_from_differential_m4C <- deferential_methylated_form(ecoli_m4C_position_clean_differntial, ecoli_gene_body)

ecoli_promoter_gene_body_differential_m4C <- rbind(ecoli_promoter_methyl_from_differential_m4C, ecoli_gene_body_methyl_from_differential_m4C)
ecoli_promoter_gene_body_differential_m4C_gene_id <- sub("^GeneID:", "", unique(ecoli_promoter_gene_body_differential_m4C$id))

###### m5c
ecoli_promoter_methyl_from_differential_m5C <- deferential_methylated_form(ecoli_m5C_position_clean_differntial, ecoli_mRNA_promoter)
ecoli_gene_body_methyl_from_differential_m5C <- deferential_methylated_form(ecoli_m5C_position_clean_differntial, ecoli_gene_body)

ecoli_promoter_gene_body_differential_m5C <- rbind(ecoli_promoter_methyl_from_differential_m5C, ecoli_gene_body_methyl_from_differential_m5C)
ecoli_promoter_gene_body_differential_m5C_gene_id <- sub("^GeneID:", "", unique(ecoli_promoter_gene_body_differential_m5C$id))


ecoli_promoter_gene_body_differential_all <- rbind(ecoli_promoter_gene_body_differential_m6A, ecoli_promoter_gene_body_differential_m4C, ecoli_promoter_gene_body_differential_m5C)
ecoli_promoter_gene_body_differential_all_gene_id <- sub("^GeneID:", "", unique(ecoli_promoter_gene_body_differential_all$id))

ecoli_motif_differntial <- rbind(ecoli_m4C_position_clean_differntial, ecoli_m5C_position_clean_differntial, ecoli_m6A_position_clean_differntial)

#### perform file cleaning and methylation region tageting only on differential sties on lactobacillus
lacidophilus_m6A_position_clean <- position_clean(lacidophilus_position[lacidophilus_position$modified_base_code=="a",], lacidophilus_dmr_methyl_phase_6mA)
lacidophilus_m6A_position_clean <- group_name_change(lacidophilus_m6A_position_clean, "exp", "sta")
lacidophilus_m6A_position_clean_differntial <- lacidophilus_m6A_position_clean[lacidophilus_m6A_position_clean$differential=="yes",]

###### m6a
lacidophilus_promoter_methyl_from_differential_m6A <- deferential_methylated_form(lacidophilus_m6A_position_clean_differntial, lacidophilus_mRNA_promoter)
lacidophilus_gene_body_methyl_from_differential_m6A <- deferential_methylated_form(lacidophilus_m6A_position_clean_differntial, lacidophilus_gene_body)

lacidophilus_motif_differntial <- lacidophilus_m6A_position_clean_differntial

#############################################################################
#### comparing locus and motif methods on differntially methylaated gene identification
setwd("")
ecoli_all_differntial <- fread("ecoli_position_clean_differntial.tsv", sep = "\t", header = T)
lacidophilus_all_differntial <- fread("lacidophilus_position_clean_differntial.tsv", sep = "\t", header = T)

ecoli_motif_differntial <- fread("ecoli_motif_clean_differntial.tsv", sep = "\t", header = T)
lacidophilus_motif_differntial <- fread("lacidophilus_motif_clean_differntial.tsv", sep = "\t", header = T)


ecoli_all_differntial <- unique_id_generation(ecoli_all_differntial)
lacidophilus_all_differntial <- unique_id_generation(lacidophilus_all_differntial)

ecoli_motif_differntial <- unique_id_generation(ecoli_motif_differntial)
lacidophilus_motif_differntial <- unique_id_generation(lacidophilus_motif_differntial)


ecoli_motif_differntial_m6a <- ecoli_motif_differntial[ecoli_motif_differntial$code == "a",]
ecoli_motif_differntial_m4c <- ecoli_motif_differntial[ecoli_motif_differntial$code == "21839",]
ecoli_motif_differntial_m5c <- ecoli_motif_differntial[ecoli_motif_differntial$code == "m",]


ecoli_motif_differntial_m6a_m4c <- ecoli_motif_differntial[ecoli_motif_differntial$code == "a" | ecoli_motif_differntial$code == "21839",]
ecoli_motif_differntial_m6c_m5c <- ecoli_motif_differntial[ecoli_motif_differntial$code == "a" | ecoli_motif_differntial$code == "m",]
ecoli_motif_differntial_m4c_m5c <- ecoli_motif_differntial[ecoli_motif_differntial$code == "21839" | ecoli_motif_differntial$code == "m",]


ecoli_all_vs_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial)
lacidpphilus_all_vs_motif <- list_generation(lacidophilus_all_differntial, lacidophilus_motif_differntial)

ecoli_all_vs_m6a_m4c_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m6a_m4c)
ecoli_all_vs_m6a_m5c_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m6c_m5c)
ecoli_all_vs_m4c_m5c_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m4c_m5c)

ecoli_all_vs_m6a_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m6a)
ecoli_all_vs_m4c_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m4c)
ecoli_all_vs_m5c_motif <- list_generation(ecoli_all_differntial, ecoli_motif_differntial_m5c)


ecoli_genome_size <- 5498578+3306+92721
lacidophilus_genome_size <- 1978847

#############################################################################
#### visualization
#### e. coli
ecoli_all_vs_m6a_motif_venn <- venn_graphing(ecoli_all_vs_m6a_motif, "G-m6A-TC") +
  labs(tag = "A") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m4c_motif_venn <- venn_graphing(ecoli_all_vs_m4c_motif, "GATCNT-m4C") +
  labs(tag = "B") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m5c_motif_venn <- venn_graphing(ecoli_all_vs_m5c_motif, "C-m5C-WGG") +
  labs(tag = "C") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m6a_m4c_motif_venn <- venn_graphing(ecoli_all_vs_m6a_m4c_motif, "G-m6A-TC, GATCNT-m4C") +
  labs(tag = "D") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m6a_m5c_motif_venn <- venn_graphing(ecoli_all_vs_m6a_m5c_motif, "G-m6A-TC, C-m5C-WGG") +
  labs(tag = "E") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m4c_m5c_motif_venn <- venn_graphing(ecoli_all_vs_m4c_m5c_motif, "GATCNT-m4C, C-m5C-WGG") +
  labs(tag = "F") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_motif_venn <- venn_graphing(ecoli_all_vs_motif, "G-m6A-TC, GATCNT-m4C, C-m5C-WGG") +
  labs(tag = "G") +
  theme(plot.tag = element_text(face = "bold")) +
  theme(text = element_text(size = 20))

ecoli_all_vs_m6a_motif_venn + ecoli_all_vs_m4c_motif_venn + ecoli_all_vs_m5c_motif_venn +
  ecoli_all_vs_m6a_m4c_motif_venn + ecoli_all_vs_m6a_m5c_motif_venn + ecoli_all_vs_m4c_m5c_motif_venn +
  ecoli_all_vs_motif_venn + plot_layout(nrow = 3, ncol=3, heights = c(1,1,1), widths = c(1,1,1))

#### l. acidophilus
lacidpphilus_all_vs_motif_venn <- venn_graphing(lacidpphilus_all_vs_motif, "GC-m6A-TC")

#############################################################################
#### fisher exact test
fisher_exact_test(ecoli_all_vs_motif, ecoli_genome_size)[2]
fisher_exact_test(lacidpphilus_all_vs_motif, lacidophilus_genome_size)[2]

fisher_exact_test(ecoli_all_vs_m6a_m4c_motif, ecoli_genome_size)[2]
fisher_exact_test(ecoli_all_vs_m6a_m5c_motif, ecoli_genome_size)[2]
fisher_exact_test(ecoli_all_vs_m4c_m5c_motif, ecoli_genome_size)[2]

fisher_exact_test(ecoli_all_vs_m6a_motif, ecoli_genome_size)[2]
fisher_exact_test(ecoli_all_vs_m4c_motif, ecoli_genome_size)[2]
fisher_exact_test(ecoli_all_vs_m5c_motif, ecoli_genome_size)[2]

fisher_exact_test(ecoli_all_vs_m6a_motif, ecoli_genome_size)[1]
fisher_exact_test(ecoli_all_vs_m4c_motif, ecoli_genome_size)[1]
fisher_exact_test(ecoli_all_vs_m5c_motif, ecoli_genome_size)[1]

fisher_exact_test(ecoli_all_vs_m6a_m4c_motif, ecoli_genome_size)[1]
fisher_exact_test(ecoli_all_vs_m6a_m5c_motif, ecoli_genome_size)[1]
fisher_exact_test(ecoli_all_vs_m4c_m5c_motif, ecoli_genome_size)[1]

fisher_exact_test(ecoli_all_vs_motif, ecoli_genome_size)[1]
fisher_exact_test(lacidpphilus_all_vs_motif, lacidophilus_genome_size)[1]